version: '3'

vars:
  IMAGE_NAME: ghcr.io/fzymgc-house/router-hosts
  IMAGE_TAG: '{{.IMAGE_TAG | default "dev"}}'
  # Local-only image name (no registry prefix) to prevent testcontainers pull attempts
  LOCAL_IMAGE: 'router-hosts:e2e-local'

tasks:
  # ─────────────────────────────────────────────────────────────
  # Development
  # ─────────────────────────────────────────────────────────────
  build:
    desc: Build all crates in debug mode
    cmds:
      - cargo build --workspace

  build:release:
    desc: Build all crates in release mode
    cmds:
      - cargo build --workspace --release

  test:
    desc: Run unit and integration tests with nextest
    cmds:
      - cargo nextest run --workspace --exclude router-hosts-e2e

  test:all:
    desc: Run all tests including doc tests
    cmds:
      - cargo nextest run --workspace --exclude router-hosts-e2e
      - cargo test --workspace --exclude router-hosts-e2e --doc

  test:sqlite:
    desc: Run SQLite backend tests
    cmds:
      - cargo nextest run -p router-hosts-storage --features sqlite -E 'test(sqlite)'

  test:postgres:
    desc: Run PostgreSQL backend tests (requires Docker for testcontainers)
    cmds:
      - cargo nextest run -p router-hosts-storage --features postgres -E 'test(postgres)'

  test:coverage:
    desc: Run tests with llvm-cov coverage report (excludes E2E)
    cmds:
      - cargo llvm-cov nextest --workspace --exclude router-hosts-e2e --html --output-dir coverage

  test:coverage:ci:
    desc: Run tests with coverage (CI mode - enforces 80% threshold)
    cmds:
      # Excluded from coverage (require network/integration infrastructure, tested by E2E):
      # - main.rs: entry point (standard exclusion)
      # - client/grpc.rs: gRPC client wrapper (requires live server)
      # - server/mod.rs: gRPC server impl (requires network binding)
      - >-
        cargo llvm-cov nextest --workspace --exclude router-hosts-e2e
        --html --output-dir coverage
        --fail-under-lines 80
        --ignore-filename-regex "(main\.rs|client/grpc\.rs|server/mod\.rs)"

  test:coverage:report:
    desc: Show coverage summary in terminal
    cmds:
      - cargo llvm-cov nextest --workspace --exclude router-hosts-e2e

  lint:
    desc: Run all linters (clippy, fmt, buf)
    cmds:
      - cargo fmt --check
      - cargo clippy --workspace -- -D warnings
      - buf lint
      - buf format --diff --exit-code

  fmt:
    desc: Format all code
    cmds:
      - cargo fmt
      - buf format -w

  # ─────────────────────────────────────────────────────────────
  # Docker
  # ─────────────────────────────────────────────────────────────
  docker:build:
    desc: Build server Docker image for local architecture
    cmds:
      - docker build -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} -t {{.LOCAL_IMAGE}} .

  docker:build-ci:
    desc: Build Docker image using pre-built binary (for CI/E2E)
    deps: ["build:release"]
    cmds:
      # Copy binary to root to avoid .dockerignore excluding target/
      - cp target/release/router-hosts router-hosts
      - docker build -f Dockerfile.ci -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} -t {{.LOCAL_IMAGE}} .
      - rm router-hosts

  docker:run:
    desc: Run server container (requires certs in ./dev/certs/)
    cmds:
      - |
        docker run --rm -it \
          -v {{.USER_WORKING_DIR}}/dev/certs:/certs:ro \
          -v {{.USER_WORKING_DIR}}/dev/data:/data \
          -p 50051:50051 \
          {{.IMAGE_NAME}}:{{.IMAGE_TAG}} \
          server --config /certs/server.toml

  # ─────────────────────────────────────────────────────────────
  # E2E Tests
  # ─────────────────────────────────────────────────────────────
  e2e:
    desc: Run E2E acceptance tests
    deps: ["docker:build", "build:release"]
    env:
      # Use local-only image name to prevent testcontainers from trying to pull
      ROUTER_HOSTS_IMAGE: '{{.LOCAL_IMAGE}}'
      ROUTER_HOSTS_BINARY: '{{.USER_WORKING_DIR}}/target/release/router-hosts'
    cmds:
      - cargo test -p router-hosts-e2e --release -- --test-threads=2

  e2e:quick:
    desc: Run E2E tests (skip rebuild, assumes image exists)
    env:
      # Use local-only image name to prevent testcontainers from trying to pull
      ROUTER_HOSTS_IMAGE: '{{.LOCAL_IMAGE}}'
      ROUTER_HOSTS_BINARY: '{{.USER_WORKING_DIR}}/target/release/router-hosts'
    cmds:
      - cargo test -p router-hosts-e2e --release -- --test-threads=2

  e2e:scenario:
    desc: Run specific E2E scenario (e.g., task e2e:scenario -- daily_operations)
    env:
      # Use local-only image name to prevent testcontainers from trying to pull
      ROUTER_HOSTS_IMAGE: '{{.LOCAL_IMAGE}}'
      ROUTER_HOSTS_BINARY: '{{.USER_WORKING_DIR}}/target/release/router-hosts'
    cmds:
      - cargo test -p router-hosts-e2e --release -- {{.CLI_ARGS}}

  # ─────────────────────────────────────────────────────────────
  # CI Shortcuts
  # ─────────────────────────────────────────────────────────────
  ci:
    desc: Run full CI pipeline locally
    cmds:
      - task: lint
      - task: test
      - task: e2e

  pre-commit:
    desc: Quick checks before committing
    cmds:
      - task: fmt
      - task: lint
      - task: test
