package server

import (
	"context"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/samber/oops"

	"github.com/fzymgc-house/router-hosts/internal/domain"
	"github.com/fzymgc-house/router-hosts/internal/storage"
)

// DnsmasqConfGenerator writes a dnsmasq conf-dir file of authoritative
// local=/address= directives atomically.
//
// For each managed name it emits a pair:
//
//	local=/<name>/
//	address=/<name>/<ip>
//
// The address= line answers the matching record type (A for an IPv4 ip, AAAA
// for an IPv6 ip) from the directive. The companion local= line makes dnsmasq
// authoritative for that exact name so queries for the *other* record type
// return NODATA instead of being forwarded upstream. The local= line is
// required because dnsmasq 2.86+ forwards non-matching record types upstream
// when only address= is present; without it, an AAAA query for an A-only name
// would leak a public AAAA in split-horizon setups. Both directives are scoped
// per-name (not zone-wide like local=/<domain>/, which would NXDOMAIN unmanaged
// names in the zone). See GH #325.
type DnsmasqConfGenerator struct {
	path string
}

// NewDnsmasqConfGenerator creates a generator that writes to the given path.
func NewDnsmasqConfGenerator(path string) *DnsmasqConfGenerator {
	return &DnsmasqConfGenerator{path: path}
}

// Regenerate loads all entries from the store, formats them as dnsmasq
// directives, and atomically writes the result. Returns the entry count.
func (g *DnsmasqConfGenerator) Regenerate(ctx context.Context, store storage.Storage) (int, error) {
	entries, err := store.ListAll(ctx)
	if err != nil {
		return 0, oops.Wrapf(err, "list hosts for dnsmasq regeneration")
	}

	content := g.FormatConf(entries)
	if err := atomicWriteFile(g.path, content); err != nil {
		return 0, err
	}
	return len(entries), nil
}

// FormatConf renders entries as dnsmasq local=/address= directive pairs, one
// pair per name and per alias. Each entry's comment/tags are emitted as a
// preceding comment line for parity with the hosts(5) output.
func (g *DnsmasqConfGenerator) FormatConf(entries []domain.HostEntry) string {
	var b strings.Builder

	now := time.Now().UTC()
	fmt.Fprintf(&b, "# Generated by router-hosts\n")
	fmt.Fprintf(&b, "# Last updated: %s\n", now.Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintf(&b, "# Entry count: %d\n\n", len(entries))

	// Sort entries by IP then hostname for deterministic output
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].IP != entries[j].IP {
			return entries[i].IP < entries[j].IP
		}
		return entries[i].Hostname < entries[j].Hostname
	})

	for _, e := range entries {
		// Per-entry comment/tags line, reusing the hosts formatter for parity.
		if suffix := formatSuffix(e.Comment, e.Tags); suffix != "" {
			b.WriteString(suffix)
			b.WriteByte('\n')
		}

		writeNameDirectives(&b, e.Hostname, e.IP)

		// Aliases sorted alphabetically, each as its own directive pair.
		if len(e.Aliases) > 0 {
			sorted := make([]string, len(e.Aliases))
			copy(sorted, e.Aliases)
			sort.Strings(sorted)
			for _, a := range sorted {
				writeNameDirectives(&b, a, e.IP)
			}
		}
	}

	return b.String()
}

// writeNameDirectives writes the "local=/<name>/" + "address=/<name>/<ip>"
// directive pair that makes dnsmasq authoritative for the name.
func writeNameDirectives(b *strings.Builder, name, ip string) {
	b.WriteString("local=/")
	b.WriteString(name)
	b.WriteString("/\n")
	b.WriteString("address=/")
	b.WriteString(name)
	b.WriteByte('/')
	b.WriteString(ip)
	b.WriteByte('\n')
}
