package server

import (
	"context"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/oklog/ulid/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/fzymgc-house/router-hosts/internal/domain"
	"github.com/fzymgc-house/router-hosts/internal/storage/sqlite"
)

func TestFormatConf_Empty(t *testing.T) {
	gen := NewDnsmasqConfGenerator("/tmp/test.conf")
	content := gen.FormatConf(nil)

	assert.Contains(t, content, "# Generated by router-hosts")
	assert.Contains(t, content, "# Entry count: 0")
	assert.NotContains(t, content, "address=/")
	assert.NotContains(t, content, "local=/")
}

func TestFormatConf_BasicEntries(t *testing.T) {
	gen := NewDnsmasqConfGenerator("/tmp/test.conf")
	comment := "NAS storage"
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "192.168.1.10",
			Hostname: "server.local",
		},
		{
			ID:       ulid.Make(),
			IP:       "192.168.1.20",
			Hostname: "nas.local",
			Comment:  &comment,
			Tags:     []string{"homelab"},
		},
	}

	content := gen.FormatConf(entries)
	assert.Contains(t, content, "# Entry count: 2")
	// Each name gets a local=/address= pair.
	assert.Contains(t, content, "local=/server.local/\naddress=/server.local/192.168.1.10\n")
	// Comment/tags emitted on the line above the directive pair.
	assert.Contains(t, content, "# NAS storage [homelab]\nlocal=/nas.local/\naddress=/nas.local/192.168.1.20\n")
}

// TestFormatConf_Golden pins the exact end-to-end output: header block, blank
// separator, per-entry comment line, directive ordering, and multi-tag join.
func TestFormatConf_Golden(t *testing.T) {
	gen := NewDnsmasqConfGenerator("/tmp/test.conf")
	comment := "primary auth host"
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "192.168.20.145",
			Hostname: "auth.fzymgc.house",
			Aliases:  []string{"sso.fzymgc.house"},
			Comment:  &comment,
			Tags:     []string{"prod", "internal"},
		},
	}

	content := gen.FormatConf(entries)

	// Strip the volatile "Last updated" line before comparing.
	var kept []string
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "# Last updated:") {
			continue
		}
		kept = append(kept, line)
	}
	got := strings.Join(kept, "\n")

	want := "# Generated by router-hosts\n" +
		"# Entry count: 1\n" +
		"\n" +
		"# primary auth host [prod, internal]\n" +
		"local=/auth.fzymgc.house/\n" +
		"address=/auth.fzymgc.house/192.168.20.145\n" +
		"local=/sso.fzymgc.house/\n" +
		"address=/sso.fzymgc.house/192.168.20.145\n"

	assert.Equal(t, want, got)
}

func TestFormatConf_AliasesEachGetDirective(t *testing.T) {
	gen := NewDnsmasqConfGenerator("/tmp/test.conf")
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "10.0.0.1",
			Hostname: "primary.local",
			Aliases:  []string{"zulu.local", "alpha.local", "mike.local"},
		},
	}

	content := gen.FormatConf(entries)
	assert.Contains(t, content, "address=/primary.local/10.0.0.1\n")
	assert.Contains(t, content, "address=/alpha.local/10.0.0.1\n")
	assert.Contains(t, content, "address=/mike.local/10.0.0.1\n")
	assert.Contains(t, content, "address=/zulu.local/10.0.0.1\n")

	// Primary hostname first, then aliases sorted alphabetically.
	primaryIdx := strings.Index(content, "address=/primary.local/")
	alphaIdx := strings.Index(content, "address=/alpha.local/")
	mikeIdx := strings.Index(content, "address=/mike.local/")
	zuluIdx := strings.Index(content, "address=/zulu.local/")
	assert.Less(t, primaryIdx, alphaIdx)
	assert.Less(t, alphaIdx, mikeIdx)
	assert.Less(t, mikeIdx, zuluIdx)
}

func TestFormatConf_EntriesSortedByIPThenHostname(t *testing.T) {
	gen := NewDnsmasqConfGenerator("/tmp/test.conf")
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "192.168.1.20", Hostname: "b.local"},
		{ID: ulid.Make(), IP: "192.168.1.10", Hostname: "z.local"},
		{ID: ulid.Make(), IP: "192.168.1.10", Hostname: "a.local"},
	}

	content := gen.FormatConf(entries)
	aIdx := strings.Index(content, "address=/a.local/")
	zIdx := strings.Index(content, "address=/z.local/")
	bIdx := strings.Index(content, "address=/b.local/")
	// 192.168.1.10 entries first (a before z by hostname), then 192.168.1.20.
	assert.Less(t, aIdx, zIdx)
	assert.Less(t, zIdx, bIdx)
}

func TestDnsmasqRegenerate(t *testing.T) {
	ctx := context.Background()

	store, err := sqlite.New("file::memory:?mode=memory&cache=shared", slog.Default())
	require.NoError(t, err)
	require.NoError(t, store.Initialize(ctx))
	t.Cleanup(func() { _ = store.Close() })

	handler := NewCommandHandler(store)
	_, err = handler.AddHost(ctx, "192.168.1.10", "server.local", nil, []string{"web"}, []string{"www.local"})
	require.NoError(t, err)

	dir := t.TempDir()
	path := filepath.Join(dir, "router-hosts.conf")
	gen := NewDnsmasqConfGenerator(path)

	count, err := gen.Regenerate(ctx, store)
	require.NoError(t, err)
	assert.Equal(t, 1, count)

	data, err := os.ReadFile(path)
	require.NoError(t, err)
	content := string(data)
	assert.Contains(t, content, "local=/server.local/\naddress=/server.local/192.168.1.10\n")
	assert.Contains(t, content, "local=/www.local/\naddress=/www.local/192.168.1.10\n")
}

func TestDnsmasqRegenerate_InvalidPath(t *testing.T) {
	ctx := context.Background()

	store, err := sqlite.New("file::memory:?mode=memory&cache=shared", slog.Default())
	require.NoError(t, err)
	require.NoError(t, store.Initialize(ctx))
	t.Cleanup(func() { _ = store.Close() })

	gen := NewDnsmasqConfGenerator("/nonexistent/dir/router-hosts.conf")
	_, err = gen.Regenerate(ctx, store)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "create temp file")
}
