package server

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/samber/oops"

	"github.com/fzymgc-house/router-hosts/internal/domain"
	"github.com/fzymgc-house/router-hosts/internal/storage"
)

// HostsFileGenerator writes hosts(5) files atomically.
type HostsFileGenerator struct {
	path string
}

// NewHostsFileGenerator creates a generator that writes to the given path.
func NewHostsFileGenerator(path string) *HostsFileGenerator {
	return &HostsFileGenerator{path: path}
}

// Regenerate loads all entries from the store, formats them, and atomically
// writes the result to the configured path. Returns the entry count.
func (g *HostsFileGenerator) Regenerate(ctx context.Context, store storage.Storage) (int, error) {
	entries, err := store.ListAll(ctx)
	if err != nil {
		return 0, oops.Wrapf(err, "list hosts for regeneration")
	}

	content := g.FormatHostsFile(entries)
	if err := atomicWriteFile(g.path, content); err != nil {
		return 0, err
	}
	return len(entries), nil
}

// FormatHostsFile renders entries in hosts(5) format with header, inline
// comments, and tag brackets.
func (g *HostsFileGenerator) FormatHostsFile(entries []domain.HostEntry) string {
	var b strings.Builder

	now := time.Now().UTC()
	fmt.Fprintf(&b, "# Generated by router-hosts\n")
	fmt.Fprintf(&b, "# Last updated: %s\n", now.Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintf(&b, "# Entry count: %d\n\n", len(entries))

	// Sort entries by IP then hostname for deterministic output
	sort.Slice(entries, func(i, j int) bool {
		if entries[i].IP != entries[j].IP {
			return entries[i].IP < entries[j].IP
		}
		return entries[i].Hostname < entries[j].Hostname
	})

	for _, e := range entries {
		// IP + hostname
		b.WriteString(e.IP)
		b.WriteByte('\t')
		b.WriteString(e.Hostname)

		// Aliases sorted alphabetically
		if len(e.Aliases) > 0 {
			sorted := make([]string, len(e.Aliases))
			copy(sorted, e.Aliases)
			sort.Strings(sorted)
			for _, a := range sorted {
				b.WriteByte(' ')
				b.WriteString(a)
			}
		}

		// Build suffix: comment and/or tags
		suffix := formatSuffix(e.Comment, e.Tags)
		if suffix != "" {
			b.WriteByte('\t')
			b.WriteString(suffix)
		}

		b.WriteByte('\n')
	}

	return b.String()
}

// formatSuffix builds the inline "# comment [tags]" string. Line breaks in the
// comment or any tag are collapsed to spaces (sanitizeCommentField) so a crafted
// Comment/Tag cannot break out of the single-line "# ..." comment and inject
// active directives into the generated config (hosts, dnsmasq, unbound). See
// GH #349 review finding router-hosts-00b.2.
func formatSuffix(comment *string, tags []string) string {
	hasComment := comment != nil && *comment != ""
	hasTags := len(tags) > 0

	if !hasComment && !hasTags {
		return ""
	}

	var parts []string
	if hasComment {
		parts = append(parts, sanitizeCommentField(*comment))
	}
	if hasTags {
		sanitized := make([]string, len(tags))
		for i, t := range tags {
			sanitized[i] = sanitizeCommentField(t)
		}
		parts = append(parts, "["+strings.Join(sanitized, ", ")+"]")
	}

	return "# " + strings.Join(parts, " ")
}

// commentLineBreakReplacer collapses CR and LF to spaces so user-supplied
// comment/tag text stays on a single line in generated config files.
var commentLineBreakReplacer = strings.NewReplacer("\n", " ", "\r", " ")

// sanitizeCommentField strips line breaks from comment/tag text emitted as a
// "# ..." comment. Without it, a Comment or Tag containing a newline would break
// out of the comment line and inject active directives into the generated
// hosts/dnsmasq/unbound output. See GH #349 review finding router-hosts-00b.2.
func sanitizeCommentField(s string) string {
	return commentLineBreakReplacer.Replace(s)
}

// atomicWriteFile writes content to a temp file in the target directory,
// fsyncs, then renames into place. Shared by all output-file generators.
func atomicWriteFile(path, content string) error {
	f, err := os.CreateTemp(filepath.Dir(path), filepath.Base(path)+".tmp.*")
	if err != nil {
		return oops.Wrapf(err, "create temp file")
	}
	tmpPath := f.Name()

	_, writeErr := f.WriteString(content)
	if writeErr != nil {
		_ = f.Close()
		_ = os.Remove(tmpPath)
		return oops.Wrapf(writeErr, "write file")
	}

	if err := f.Sync(); err != nil {
		_ = f.Close()
		_ = os.Remove(tmpPath)
		return oops.Wrapf(err, "fsync file")
	}

	if err := f.Close(); err != nil {
		_ = os.Remove(tmpPath)
		return oops.Wrapf(err, "close file")
	}

	if err := os.Rename(tmpPath, path); err != nil {
		_ = os.Remove(tmpPath)
		return oops.Wrapf(err, "rename file")
	}

	return nil
}
