package server

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/oklog/ulid/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/fzymgc-house/router-hosts/internal/domain"
)

func TestFormatHostsFile_Empty(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")
	content := gen.FormatHostsFile(nil)

	assert.Contains(t, content, "# Generated by router-hosts")
	assert.Contains(t, content, "# Entry count: 0")
}

func TestFormatHostsFile_BasicEntries(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")
	comment := "NAS storage"
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "192.168.1.10",
			Hostname: "server.local",
		},
		{
			ID:       ulid.Make(),
			IP:       "192.168.1.20",
			Hostname: "nas.local",
			Comment:  &comment,
			Tags:     []string{"homelab"},
		},
	}

	content := gen.FormatHostsFile(entries)
	assert.Contains(t, content, "# Entry count: 2")
	assert.Contains(t, content, "192.168.1.10\tserver.local\n")
	assert.Contains(t, content, "192.168.1.20\tnas.local\t# NAS storage [homelab]\n")
}

func TestFormatHostsFile_AliasesSorted(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "10.0.0.1",
			Hostname: "primary.local",
			Aliases:  []string{"zulu.local", "alpha.local", "mike.local"},
		},
	}

	content := gen.FormatHostsFile(entries)
	assert.Contains(t, content, "10.0.0.1\tprimary.local alpha.local mike.local zulu.local\n")
}

func TestFormatHostsFile_TagsOnly(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "10.0.0.1",
			Hostname: "tagged.local",
			Tags:     []string{"prod", "web"},
		},
	}

	content := gen.FormatHostsFile(entries)
	assert.Contains(t, content, "10.0.0.1\ttagged.local\t# [prod, web]\n")
}

func TestFormatHostsFile_CommentOnly(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")
	comment := "important server"
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "10.0.0.1",
			Hostname: "srv.local",
			Comment:  &comment,
		},
	}

	content := gen.FormatHostsFile(entries)
	assert.Contains(t, content, "10.0.0.1\tsrv.local\t# important server\n")
}

func TestFormatHostsFile_CommentAndTags(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")
	comment := "main db"
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "10.0.0.5",
			Hostname: "db.local",
			Comment:  &comment,
			Tags:     []string{"prod", "data"},
		},
	}

	content := gen.FormatHostsFile(entries)
	assert.Contains(t, content, "10.0.0.5\tdb.local\t# main db [prod, data]\n")
}

func TestFormatHostsFile_EmptyComment_NoTags(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")
	empty := ""
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "10.0.0.1",
			Hostname: "bare.local",
			Comment:  &empty,
		},
	}

	content := gen.FormatHostsFile(entries)
	// Empty comment with no tags should produce no suffix
	assert.Contains(t, content, "10.0.0.1\tbare.local\n")
	assert.NotContains(t, content, "# \n")
}

func TestFormatHostsFile_NilComment_NoTags(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")
	entries := []domain.HostEntry{
		{
			ID:       ulid.Make(),
			IP:       "10.0.0.1",
			Hostname: "bare.local",
		},
	}

	content := gen.FormatHostsFile(entries)
	assert.Contains(t, content, "10.0.0.1\tbare.local\n")
	// No tab after hostname when there's no suffix
	lines := strings.Split(content, "\n")
	for _, line := range lines {
		if strings.HasPrefix(line, "10.0.0.1") {
			assert.Equal(t, "10.0.0.1\tbare.local", line)
		}
	}
}

func TestFormatHostsFile_SortedByIPThenHostname(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "192.168.1.20", Hostname: "beta.local"},
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "gamma.local"},
		{ID: ulid.Make(), IP: "192.168.1.20", Hostname: "alpha.local"},
		{ID: ulid.Make(), IP: "10.0.0.1", Hostname: "delta.local"},
	}

	content := gen.FormatHostsFile(entries)
	lines := strings.Split(content, "\n")

	// Extract entry lines (skip header)
	var entryLines []string
	for _, l := range lines {
		if l != "" && !strings.HasPrefix(l, "#") {
			entryLines = append(entryLines, l)
		}
	}

	require.Len(t, entryLines, 4)
	// Sorted by IP (lexicographic), then hostname
	assert.True(t, strings.HasPrefix(entryLines[0], "10.0.0.1\tdelta.local"))
	assert.True(t, strings.HasPrefix(entryLines[1], "10.0.0.5\tgamma.local"))
	assert.True(t, strings.HasPrefix(entryLines[2], "192.168.1.20\talpha.local"))
	assert.True(t, strings.HasPrefix(entryLines[3], "192.168.1.20\tbeta.local"))
}

func TestAtomicWrite_NewFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "hosts")
	gen := NewHostsFileGenerator(path)

	err := gen.atomicWrite("test content\n")
	require.NoError(t, err)

	data, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, "test content\n", string(data))

	// Temp file should not exist
	_, err = os.Stat(path + ".tmp")
	assert.True(t, os.IsNotExist(err))
}

func TestAtomicWrite_OverwritesExisting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "hosts")
	gen := NewHostsFileGenerator(path)

	require.NoError(t, os.WriteFile(path, []byte("old content"), 0o644))

	err := gen.atomicWrite("new content\n")
	require.NoError(t, err)

	data, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, "new content\n", string(data))
}

func TestAtomicWrite_CleansUpTmp(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "hosts")
	gen := NewHostsFileGenerator(path)

	err := gen.atomicWrite("content\n")
	require.NoError(t, err)

	// .tmp file should be gone after successful write
	_, err = os.Stat(path + ".tmp")
	assert.True(t, os.IsNotExist(err))
}
