package server

import (
	"strings"
	"testing"

	"github.com/oklog/ulid/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/fzymgc-house/router-hosts/internal/domain"
)

// TestFormatHostsFile_Golden pins FormatHostsFile's exact byte output (D-14,
// LAZY-04) against the CURRENT (pre-change) production code, since it is the
// one regeneration writer among the three (hosts file, unbound conf,
// dnsmasq conf) with no existing byte-exact golden. D-07's later ListAll
// rewrite as a drain-loop wrapper over ListPage puts this writer downstream
// of D-10's new ordering even though it does not itself migrate, so this
// fixture must hold byte-identical before and after that change lands.
func TestFormatHostsFile_Golden(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")

	first := "first"
	second := "second"

	// Fixture is supplied in deliberately NON-sorted order. Entries 2 and 3
	// share IDENTICAL IP and IDENTICAL hostname (differing only in
	// Comment), pinning the sort's tie behavior — not only its key
	// ordering — since sort.Slice is not a stable sort.
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "192.168.1.20", Hostname: "zeta.local", Tags: []string{"edge"}},
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "alpha.local", Comment: &first},
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "alpha.local", Comment: &second},
		{ID: ulid.Make(), IP: "10.0.0.1", Hostname: "delta.local", Aliases: []string{"delta-alt.local"}},
	}

	content := gen.FormatHostsFile(entries)

	// Strip the volatile "# Last updated:" line, matching TestFormatConf_Golden.
	var kept []string
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "# Last updated:") {
			continue
		}
		kept = append(kept, line)
	}
	got := strings.Join(kept, "\n")

	want := "# Generated by router-hosts\n" +
		"# Entry count: 4\n" +
		"\n" +
		"10.0.0.1\tdelta.local delta-alt.local\n" +
		"10.0.0.5\talpha.local\t# first\n" +
		"10.0.0.5\talpha.local\t# second\n" +
		"192.168.1.20\tzeta.local\t# [edge]\n"

	assert.Equal(t, want, got)

	// FormatHostsFile mutates the caller's slice order in place (observable
	// property callers may depend on) -- assert the input slice itself now
	// reflects sorted order, not just the returned string.
	require.Len(t, entries, 4)
	assert.Equal(t, "10.0.0.1", entries[0].IP)
	assert.Equal(t, "10.0.0.5", entries[1].IP)
	assert.Equal(t, "10.0.0.5", entries[2].IP)
	assert.Equal(t, "192.168.1.20", entries[3].IP)
}

// TestFormatHostsFile_Golden_ReversedInputStillSorts proves the golden's
// assertion is on RENDERED order, not input order: reversing the fixture's
// input order must leave the test green.
func TestFormatHostsFile_Golden_ReversedInputStillSorts(t *testing.T) {
	gen := NewHostsFileGenerator("/tmp/test-hosts")

	first := "first"
	second := "second"

	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.1", Hostname: "delta.local", Aliases: []string{"delta-alt.local"}},
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "alpha.local", Comment: &second},
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "alpha.local", Comment: &first},
		{ID: ulid.Make(), IP: "192.168.1.20", Hostname: "zeta.local", Tags: []string{"edge"}},
	}

	content := gen.FormatHostsFile(entries)

	var kept []string
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "# Last updated:") {
			continue
		}
		kept = append(kept, line)
	}
	got := strings.Join(kept, "\n")

	want := "# Generated by router-hosts\n" +
		"# Entry count: 4\n" +
		"\n" +
		"10.0.0.1\tdelta.local delta-alt.local\n" +
		"10.0.0.5\talpha.local\t# second\n" +
		"10.0.0.5\talpha.local\t# first\n" +
		"192.168.1.20\tzeta.local\t# [edge]\n"

	assert.Equal(t, want, got)
}
