package server

import (
	"context"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/fzymgc-house/router-hosts/internal/domain"
	"github.com/fzymgc-house/router-hosts/internal/storage"
)

// HostsFileGenerator writes hosts(5) files atomically.
type HostsFileGenerator struct {
	path string
}

// NewHostsFileGenerator creates a generator that writes to the given path.
func NewHostsFileGenerator(path string) *HostsFileGenerator {
	return &HostsFileGenerator{path: path}
}

// Regenerate loads all entries from the store, formats them, and atomically
// writes the result to the configured path. Returns the entry count.
func (g *HostsFileGenerator) Regenerate(ctx context.Context, store storage.Storage) (int, error) {
	entries, err := store.ListAll(ctx)
	if err != nil {
		return 0, fmt.Errorf("list hosts for regeneration: %w", err)
	}

	content := g.FormatHostsFile(entries)
	if err := g.atomicWrite(content); err != nil {
		return 0, err
	}
	return len(entries), nil
}

// FormatHostsFile renders entries in hosts(5) format with header, inline
// comments, and tag brackets.
func (g *HostsFileGenerator) FormatHostsFile(entries []domain.HostEntry) string {
	var b strings.Builder

	now := time.Now().UTC()
	fmt.Fprintf(&b, "# Generated by router-hosts\n")
	fmt.Fprintf(&b, "# Last updated: %s\n", now.Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintf(&b, "# Entry count: %d\n\n", len(entries))

	for _, e := range entries {
		// IP + hostname
		b.WriteString(e.IP)
		b.WriteByte('\t')
		b.WriteString(e.Hostname)

		// Aliases sorted alphabetically
		if len(e.Aliases) > 0 {
			sorted := make([]string, len(e.Aliases))
			copy(sorted, e.Aliases)
			sort.Strings(sorted)
			for _, a := range sorted {
				b.WriteByte(' ')
				b.WriteString(a)
			}
		}

		// Build suffix: comment and/or tags
		suffix := formatSuffix(e.Comment, e.Tags)
		if suffix != "" {
			b.WriteByte('\t')
			b.WriteString(suffix)
		}

		b.WriteByte('\n')
	}

	return b.String()
}

// formatSuffix builds the inline "# comment [tags]" string.
func formatSuffix(comment *string, tags []string) string {
	hasComment := comment != nil && *comment != ""
	hasTags := len(tags) > 0

	if !hasComment && !hasTags {
		return ""
	}

	var parts []string
	if hasComment {
		parts = append(parts, *comment)
	}
	if hasTags {
		parts = append(parts, "["+strings.Join(tags, ", ")+"]")
	}

	return "# " + strings.Join(parts, " ")
}

// atomicWrite writes content to a temp file, fsyncs, then renames into place.
func (g *HostsFileGenerator) atomicWrite(content string) error {
	tmpPath := g.path + ".tmp"

	f, err := os.Create(tmpPath)
	if err != nil {
		return fmt.Errorf("create temp hosts file: %w", err)
	}

	_, writeErr := f.WriteString(content)
	if writeErr != nil {
		f.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("write hosts file: %w", writeErr)
	}

	if err := f.Sync(); err != nil {
		f.Close()
		os.Remove(tmpPath)
		return fmt.Errorf("fsync hosts file: %w", err)
	}

	if err := f.Close(); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("close hosts file: %w", err)
	}

	if err := os.Rename(tmpPath, g.path); err != nil {
		os.Remove(tmpPath)
		return fmt.Errorf("rename hosts file: %w", err)
	}

	return nil
}
