package server

import (
	"context"
	"fmt"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	hostsv1 "github.com/fzymgc-house/router-hosts/api/v1/router_hosts/v1"
)

// TestExportHosts_Golden captures byte-exact output for ExportHosts' three
// formats (hosts, json, csv), including the empty-inventory case, against
// the CURRENT (pre-change) production code (D-14). This test drives the
// real ExportHosts RPC through sendExportChunks rather than reimplementing
// its render logic, so a later behavior change must keep this fixture green
// without editing it (must_haves prohibition: never re-record from
// post-change output).
func TestExportHosts_Golden(t *testing.T) {
	t.Run("hosts, json, csv formats", func(t *testing.T) {
		env := newServiceTestEnv(t)
		ctx := context.Background()

		// Fixture covers: non-nil Comment (e1, e3), nil Comment (e2, e4),
		// multiple Tags/Aliases (e1), and empty Tags/Aliases (e2, e4's
		// Aliases). IDs are real ULIDs minted by AddHost — the property
		// pinned here is layout and ordering, not the ID values, so `want`
		// is built from the seeded IDs at assert time rather than a
		// hardcoded ULID literal.
		c1 := "edge cache node"
		e1, err := env.handler.AddHost(ctx, "10.0.0.5", "cache.local", &c1,
			[]string{"prod", "cache", "edge"}, []string{"redis.local", "memcache.local"})
		require.NoError(t, err)

		e2, err := env.handler.AddHost(ctx, "10.0.0.9", "empty.local", nil, nil, nil)
		require.NoError(t, err)

		c3 := "primary auth"
		e3, err := env.handler.AddHost(ctx, "192.168.1.10", "auth.local", &c3,
			[]string{"web"}, []string{"login.local"})
		require.NoError(t, err)

		e4, err := env.handler.AddHost(ctx, "192.168.1.20", "solo.local", nil,
			[]string{"single"}, nil)
		require.NoError(t, err)

		t.Run("hosts", func(t *testing.T) {
			stream, err := env.client.ExportHosts(ctx, &hostsv1.ExportHostsRequest{Format: "hosts"})
			require.NoError(t, err)
			chunks := drainExportHosts(t, stream)
			require.Len(t, chunks, 1)
			content := string(concatChunks(chunks))

			// Strip the volatile "# Last updated:" line, matching
			// TestFormatConf_Golden's idiom.
			var kept []string
			for _, line := range strings.Split(content, "\n") {
				if strings.HasPrefix(line, "# Last updated:") {
					continue
				}
				kept = append(kept, line)
			}
			got := strings.Join(kept, "\n")

			// hosts(5) format renders no ID; entries are sorted by
			// IP-then-hostname by FormatHostsFile, which for this
			// fixture's IPs (string-compared: "10.0.0.5" < "10.0.0.9" <
			// "192.168.1.10" < "192.168.1.20") happens to match
			// insertion order.
			want := "# Generated by router-hosts\n" +
				"# Entry count: 4\n" +
				"\n" +
				"10.0.0.5\tcache.local memcache.local redis.local\t# edge cache node [prod, cache, edge]\n" +
				"10.0.0.9\tempty.local\n" +
				"192.168.1.10\tauth.local login.local\t# primary auth [web]\n" +
				"192.168.1.20\tsolo.local\t# [single]\n"

			assert.Equal(t, want, got)
		})

		t.Run("json", func(t *testing.T) {
			stream, err := env.client.ExportHosts(ctx, &hostsv1.ExportHostsRequest{Format: "json"})
			require.NoError(t, err)
			chunks := drainExportHosts(t, stream)
			require.Len(t, chunks, 1)
			got := string(concatChunks(chunks))

			// json.MarshalIndent(out, "", "  ") layout: two-space indent,
			// no trailing newline, `comment` key absent for a nil Comment
			// (json:"comment,omitempty"). Entry order is ListAll's
			// ascending-aggregate-ID order (D-10), which for this
			// fixture's freshly-minted monotonic IDs matches insertion
			// order: e1, e2, e3, e4.
			want := fmt.Sprintf(
				"[\n"+
					"  {\n"+
					"    \"id\": \"%s\",\n"+
					"    \"ip_address\": \"10.0.0.5\",\n"+
					"    \"hostname\": \"cache.local\",\n"+
					"    \"comment\": \"edge cache node\",\n"+
					"    \"tags\": [\n"+
					"      \"prod\",\n"+
					"      \"cache\",\n"+
					"      \"edge\"\n"+
					"    ],\n"+
					"    \"aliases\": [\n"+
					"      \"redis.local\",\n"+
					"      \"memcache.local\"\n"+
					"    ]\n"+
					"  },\n"+
					"  {\n"+
					"    \"id\": \"%s\",\n"+
					"    \"ip_address\": \"10.0.0.9\",\n"+
					"    \"hostname\": \"empty.local\",\n"+
					"    \"tags\": [],\n"+
					"    \"aliases\": []\n"+
					"  },\n"+
					"  {\n"+
					"    \"id\": \"%s\",\n"+
					"    \"ip_address\": \"192.168.1.10\",\n"+
					"    \"hostname\": \"auth.local\",\n"+
					"    \"comment\": \"primary auth\",\n"+
					"    \"tags\": [\n"+
					"      \"web\"\n"+
					"    ],\n"+
					"    \"aliases\": [\n"+
					"      \"login.local\"\n"+
					"    ]\n"+
					"  },\n"+
					"  {\n"+
					"    \"id\": \"%s\",\n"+
					"    \"ip_address\": \"192.168.1.20\",\n"+
					"    \"hostname\": \"solo.local\",\n"+
					"    \"tags\": [\n"+
					"      \"single\"\n"+
					"    ],\n"+
					"    \"aliases\": []\n"+
					"  }\n"+
					"]",
				e1.ID.String(), e2.ID.String(), e3.ID.String(), e4.ID.String(),
			)

			assert.Equal(t, want, got)
			// The nil-comment entries must never gain a "comment" key.
			assert.NotContains(t, got, "\"comment\": null")
		})

		t.Run("csv", func(t *testing.T) {
			stream, err := env.client.ExportHosts(ctx, &hostsv1.ExportHostsRequest{Format: "csv"})
			require.NoError(t, err)
			chunks := drainExportHosts(t, stream)
			require.Len(t, chunks, 1)
			got := string(concatChunks(chunks))

			// Header row exactly id,ip_address,hostname,comment,tags,aliases;
			// ";" as the tags/aliases joiner; empty string for a nil
			// comment. Same entry order as json (ListAll's order).
			want := fmt.Sprintf(
				"id,ip_address,hostname,comment,tags,aliases\n"+
					"%s,10.0.0.5,cache.local,edge cache node,prod;cache;edge,redis.local;memcache.local\n"+
					"%s,10.0.0.9,empty.local,,,\n"+
					"%s,192.168.1.10,auth.local,primary auth,web,login.local\n"+
					"%s,192.168.1.20,solo.local,,single,\n",
				e1.ID.String(), e2.ID.String(), e3.ID.String(), e4.ID.String(),
			)

			assert.Equal(t, want, got)
		})
	})

	// Empty-inventory sub-case: json renders exactly "[]" (never "null"),
	// csv renders the header row only, and the stream carries exactly ONE
	// ExportHostsResponse message whose Chunk is empty for "hosts". This is
	// the review-L14 empty-payload carve-out in sendExportChunks — D-03's
	// later streaming rewrite must preserve it.
	t.Run("empty inventory", func(t *testing.T) {
		env := newServiceTestEnv(t)
		ctx := context.Background()

		t.Run("json is exactly []", func(t *testing.T) {
			stream, err := env.client.ExportHosts(ctx, &hostsv1.ExportHostsRequest{Format: "json"})
			require.NoError(t, err)
			chunks := drainExportHosts(t, stream)
			// Message count is asserted independently of bytes: an
			// assertion on concatenated bytes alone cannot distinguish
			// one empty message from zero messages (review L14's exact
			// bug shape).
			require.Len(t, chunks, 1, "empty inventory must yield exactly one response message")
			got := string(concatChunks(chunks))
			assert.Equal(t, "[]", got)
			assert.Len(t, got, 2, "empty-inventory json body must be the two-byte literal []")
		})

		t.Run("csv is header row only", func(t *testing.T) {
			stream, err := env.client.ExportHosts(ctx, &hostsv1.ExportHostsRequest{Format: "csv"})
			require.NoError(t, err)
			chunks := drainExportHosts(t, stream)
			require.Len(t, chunks, 1, "empty inventory must yield exactly one response message")
			got := string(concatChunks(chunks))
			assert.Equal(t, "id,ip_address,hostname,comment,tags,aliases\n", got)
		})
	})
}
