package server

import (
	"context"
	"fmt"
	"net"
	"sort"
	"strings"
	"time"

	"github.com/samber/oops"

	"github.com/fzymgc-house/router-hosts/internal/domain"
	"github.com/fzymgc-house/router-hosts/internal/storage"
)

// defaultUnboundTTL is used when the configured TTL is unset or non-positive.
const defaultUnboundTTL = 300

// UnboundConfGenerator writes an unbound conf-dir file of authoritative
// local-zone/local-data directives atomically. For each managed name it emits
// one:
//
//	local-zone: "<fqdn>." static
//
// followed by one `local-data` line per address:
//
//	local-data: "<fqdn>. <ttl> IN A|AAAA <ip>"
//
// A `static` zone answers the listed record types and returns NODATA for any
// other type at that name (NXDOMAIN for names with no local-data), so a name's
// missing types are never forwarded upstream — closing the HTTPS/type-65 ECH +
// AAAA leak class. Records for one name are grouped across host entries: because
// domain.HostEntry carries a single IP, a dual-stack host is two entries sharing
// a hostname, and both fold into one local-zone. See GH #349.
type UnboundConfGenerator struct {
	path string
	ttl  int
}

// NewUnboundConfGenerator creates a generator writing to path. A ttl <= 0 is
// normalized to defaultUnboundTTL.
func NewUnboundConfGenerator(path string, ttl int) *UnboundConfGenerator {
	if ttl <= 0 {
		ttl = defaultUnboundTTL
	}
	return &UnboundConfGenerator{path: path, ttl: ttl}
}

// Regenerate loads all entries, formats them, and atomically writes the result.
// Returns the entry count.
func (g *UnboundConfGenerator) Regenerate(ctx context.Context, store storage.Storage) (int, error) {
	entries, err := store.ListAll(ctx)
	if err != nil {
		return 0, oops.Wrapf(err, "list hosts for unbound regeneration")
	}
	content := g.FormatConf(entries)
	if err := atomicWriteFile(g.path, content); err != nil {
		return 0, err
	}
	return len(entries), nil
}

// unboundName accumulates the addresses and comment lines for one zone name.
type unboundName struct {
	ips      []string
	seenIP   map[string]bool
	comments []string
	seenCmt  map[string]bool
}

// FormatConf renders entries as grouped unbound local-zone/local-data blocks,
// one block per unique name (hostname + each alias), sorted by FQDN. Output is a
// pure function of the entry set (records and comments sorted), independent of
// input order, for stable diffs.
func (g *UnboundConfGenerator) FormatConf(entries []domain.HostEntry) string {
	var b strings.Builder

	now := time.Now().UTC()
	fmt.Fprintf(&b, "# Generated by router-hosts\n")
	fmt.Fprintf(&b, "# Last updated: %s\n", now.Format("2006-01-02 15:04:05 UTC"))
	fmt.Fprintf(&b, "# Entry count: %d\n\n", len(entries))

	names := make(map[string]*unboundName)
	var order []string
	add := func(rawName, ip, suffix string) {
		key := normalizeFQDN(rawName)
		// Canonicalize the address so an IPv4-mapped IPv6 literal (e.g.
		// "::ffff:10.0.0.5") is emitted in the dotted-quad form its A record
		// requires — rrType classifies it as A, and an un-normalized literal
		// would produce a malformed local-data line unbound rejects. Also
		// dedupes equivalent spellings. See GH #349 finding router-hosts-00b.4.
		if parsed := net.ParseIP(ip); parsed != nil {
			ip = parsed.String()
		}
		agg, ok := names[key]
		if !ok {
			agg = &unboundName{seenIP: map[string]bool{}, seenCmt: map[string]bool{}}
			names[key] = agg
			order = append(order, key)
		}
		if !agg.seenIP[ip] {
			agg.seenIP[ip] = true
			agg.ips = append(agg.ips, ip)
		}
		if suffix != "" && !agg.seenCmt[suffix] {
			agg.seenCmt[suffix] = true
			agg.comments = append(agg.comments, suffix)
		}
	}

	for _, e := range entries {
		suffix := formatSuffix(e.Comment, e.Tags)
		add(e.Hostname, e.IP, suffix)
		for _, a := range e.Aliases {
			add(a, e.IP, suffix)
		}
	}

	sort.Strings(order)
	for _, key := range order {
		agg := names[key]
		sort.Strings(agg.comments)
		for _, c := range agg.comments {
			b.WriteString(c)
			b.WriteByte('\n')
		}
		fmt.Fprintf(&b, "local-zone: %q static\n", key)
		sort.Slice(agg.ips, func(i, j int) bool {
			ti, tj := rrType(agg.ips[i]), rrType(agg.ips[j])
			if ti != tj {
				return ti == "A" // A before AAAA
			}
			return agg.ips[i] < agg.ips[j]
		})
		for _, ip := range agg.ips {
			data := fmt.Sprintf("%s %d IN %s %s", key, g.ttl, rrType(ip), ip)
			fmt.Fprintf(&b, "local-data: %q\n", data)
		}
	}

	return b.String()
}

// normalizeFQDN strips any trailing dots and appends exactly one, so a name
// stored with or without a trailing dot yields the same zone name.
func normalizeFQDN(name string) string {
	return strings.TrimRight(name, ".") + "."
}

// rrType returns "A" for an IPv4 address, "AAAA" otherwise. dnsmasq's address=
// directive is type-agnostic, so the sibling generator needs no such helper;
// unbound's local-data must name the type explicitly.
func rrType(ip string) string {
	if net.ParseIP(ip).To4() != nil {
		return "A"
	}
	return "AAAA"
}
