package server

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/oklog/ulid/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/fzymgc-house/router-hosts/internal/domain"
	"github.com/fzymgc-house/router-hosts/internal/storage/sqlite"
)

func TestUnboundFormatConf_Empty(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	content := gen.FormatConf(nil)

	assert.Contains(t, content, "# Generated by router-hosts")
	assert.Contains(t, content, "# Entry count: 0")
	assert.NotContains(t, content, "local-zone:")
	assert.NotContains(t, content, "local-data:")
}

func TestUnboundFormatConf_SingleA(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "api.fzymgc.house"},
	}
	content := gen.FormatConf(entries)
	assert.Contains(t, content, "local-zone: \"api.fzymgc.house.\" static\n")
	assert.Contains(t, content, "local-data: \"api.fzymgc.house. 300 IN A 10.0.0.5\"\n")
}

func TestUnboundFormatConf_IPv6AAAA(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "fd00::5", Hostname: "api.fzymgc.house"},
	}
	content := gen.FormatConf(entries)
	assert.Contains(t, content, "local-data: \"api.fzymgc.house. 300 IN AAAA fd00::5\"\n")
}

// Dual-stack: two entries, same hostname, v4 + v6 => ONE local-zone, both
// local-data (A before AAAA), deduped-union comments (sorted).
func TestUnboundFormatConf_DualStackGrouping(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	cA := "role=api"
	cV6 := "ipv6-managed"
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "api.fzymgc.house", Comment: &cA},
		{ID: ulid.Make(), IP: "fd00::5", Hostname: "api.fzymgc.house", Comment: &cV6},
	}
	content := gen.FormatConf(entries)
	assert.Equal(t, 1, strings.Count(content, "local-zone: \"api.fzymgc.house.\" static"))
	assert.Contains(t, content, "# ipv6-managed\n# role=api\nlocal-zone: \"api.fzymgc.house.\" static\n"+
		"local-data: \"api.fzymgc.house. 300 IN A 10.0.0.5\"\n"+
		"local-data: \"api.fzymgc.house. 300 IN AAAA fd00::5\"\n")
}

func TestUnboundFormatConf_Golden(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	cA := "role=api"
	cV6 := "ipv6-managed"
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "api.fzymgc.house", Comment: &cA},
		{ID: ulid.Make(), IP: "fd00::5", Hostname: "api.fzymgc.house", Comment: &cV6},
		{ID: ulid.Make(), IP: "10.0.0.9", Hostname: "db.fzymgc.house", Aliases: []string{"sql.fzymgc.house"}},
	}
	content := gen.FormatConf(entries)

	var kept []string
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "# Last updated:") {
			continue
		}
		kept = append(kept, line)
	}
	got := strings.Join(kept, "\n")

	want := "# Generated by router-hosts\n" +
		"# Entry count: 3\n" +
		"\n" +
		"server:\n" +
		"# ipv6-managed\n" +
		"# role=api\n" +
		"local-zone: \"api.fzymgc.house.\" static\n" +
		"local-data: \"api.fzymgc.house. 300 IN A 10.0.0.5\"\n" +
		"local-data: \"api.fzymgc.house. 300 IN AAAA fd00::5\"\n" +
		"local-zone: \"db.fzymgc.house.\" static\n" +
		"local-data: \"db.fzymgc.house. 300 IN A 10.0.0.9\"\n" +
		"local-zone: \"sql.fzymgc.house.\" static\n" +
		"local-data: \"sql.fzymgc.house. 300 IN A 10.0.0.9\"\n"

	assert.Equal(t, want, got)
}

// The file must open a server: clause before any local-zone:/local-data:
// directive, since those are server:-scope options. Without the header, unbound
// rejects the file with a syntax error at the first local-zone: when it is
// pulled in via a top-level include: (the documented Firewalla unbound_local/
// layout), and silently never loads the generated zone. Regression for GH #354.
func TestUnboundFormatConf_ServerClauseHeader(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "api.fzymgc.house"},
	}
	content := gen.FormatConf(entries)

	serverIdx := strings.Index(content, "server:\n")
	require.NotEqual(t, -1, serverIdx, "output must contain a server: clause header")

	zoneIdx := strings.Index(content, "local-zone:")
	require.NotEqual(t, -1, zoneIdx, "output must contain a local-zone: directive")
	assert.Less(t, serverIdx, zoneIdx,
		"server: header must precede the first local-zone: directive")
}

func TestUnboundFormatConf_TrailingDotIdempotent(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "foo.fzymgc.house."},
	}
	content := gen.FormatConf(entries)
	assert.Contains(t, content, "local-zone: \"foo.fzymgc.house.\" static\n")
	assert.NotContains(t, content, "fzymgc.house..")
}

func TestUnboundFormatConf_BareAliasPseudoTLD(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "host.fzymgc.house", Aliases: []string{"host"}},
	}
	content := gen.FormatConf(entries)
	assert.Contains(t, content, "local-zone: \"host.\" static\n")
	assert.Contains(t, content, "local-data: \"host. 300 IN A 10.0.0.5\"\n")
}

func TestUnboundFormatConf_RoundRobin(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.2", Hostname: "web.fzymgc.house"},
		{ID: ulid.Make(), IP: "10.0.0.1", Hostname: "web.fzymgc.house"},
	}
	content := gen.FormatConf(entries)
	assert.Equal(t, 1, strings.Count(content, "local-zone: \"web.fzymgc.house.\" static"))
	assert.Contains(t, content, "local-data: \"web.fzymgc.house. 300 IN A 10.0.0.1\"\n"+
		"local-data: \"web.fzymgc.house. 300 IN A 10.0.0.2\"\n")
}

func TestUnboundFormatConf_TTLApplied(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 600)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "api.fzymgc.house"},
	}
	assert.Contains(t, gen.FormatConf(entries), "IN A 10.0.0.5\"")
	assert.Contains(t, gen.FormatConf(entries), "api.fzymgc.house. 600 IN A 10.0.0.5")
}

func TestUnboundFormatConf_SortedByFQDN(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.3", Hostname: "zeta.fzymgc.house"},
		{ID: ulid.Make(), IP: "10.0.0.1", Hostname: "alpha.fzymgc.house"},
	}
	content := gen.FormatConf(entries)
	assert.Less(t,
		strings.Index(content, "alpha.fzymgc.house."),
		strings.Index(content, "zeta.fzymgc.house."))
}

// Two entries contributing the SAME comment to one name emit it once (dedup).
func TestUnboundFormatConf_CommentDedup(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	c := "role=api"
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "api.fzymgc.house", Comment: &c},
		{ID: ulid.Make(), IP: "fd00::5", Hostname: "api.fzymgc.house", Comment: &c},
	}
	content := gen.FormatConf(entries)
	assert.Equal(t, 1, strings.Count(content, "local-zone: \"api.fzymgc.house.\" static"))
	assert.Equal(t, 1, strings.Count(content, "# role=api\n"))
}

// An entry with Tags but no Comment exercises the tags-only formatSuffix branch.
func TestUnboundFormatConf_TagsOnlyComment(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "api.fzymgc.house", Tags: []string{"prod", "edge"}},
	}
	content := gen.FormatConf(entries)
	assert.Contains(t, content, "# [prod, edge]\nlocal-zone: \"api.fzymgc.house.\" static\n")
}

// A newline in a Comment must not break out of the "# ..." line and inject an
// active directive. Regression for GH #349 finding router-hosts-00b.2.
func TestUnboundFormatConf_CommentNewlineSanitized(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	evil := "ok\nlocal-zone: \"evil.example.\" static"
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "10.0.0.5", Hostname: "api.fzymgc.house", Comment: &evil},
	}
	content := gen.FormatConf(entries)
	// No injected directive as an active (non-comment) line.
	assert.NotContains(t, content, "\nlocal-zone: \"evil.example.\" static")
	// The comment is collapsed onto a single line.
	assert.Contains(t, content, "# ok local-zone: \"evil.example.\" static\n")
}

// An IPv4-mapped IPv6 literal is emitted in dotted-quad form for its A record.
// Regression for GH #349 finding router-hosts-00b.4.
func TestUnboundFormatConf_IPv4MappedIPv6Canonicalized(t *testing.T) {
	gen := NewUnboundConfGenerator("/tmp/unbound.conf", 0)
	entries := []domain.HostEntry{
		{ID: ulid.Make(), IP: "::ffff:10.0.0.5", Hostname: "api.fzymgc.house"},
	}
	content := gen.FormatConf(entries)
	assert.Contains(t, content, "local-data: \"api.fzymgc.house. 300 IN A 10.0.0.5\"\n")
	assert.NotContains(t, content, "::ffff:")
}

func TestUnboundRegenerate(t *testing.T) {
	ctx := context.Background()

	store, err := sqlite.New(fmt.Sprintf("file:%s?mode=memory&cache=shared", t.Name()), slog.Default())
	require.NoError(t, err)
	require.NoError(t, store.Initialize(ctx))
	t.Cleanup(func() { _ = store.Close() })

	handler := NewCommandHandler(store)
	_, err = handler.AddHost(ctx, "10.0.0.5", "api.fzymgc.house", nil, []string{"web"}, []string{"sso.fzymgc.house"})
	require.NoError(t, err)

	dir := t.TempDir()
	path := filepath.Join(dir, "router-hosts.conf")
	gen := NewUnboundConfGenerator(path, 0)

	count, err := gen.Regenerate(ctx, store)
	require.NoError(t, err)
	assert.Equal(t, 1, count)

	data, err := os.ReadFile(path)
	require.NoError(t, err)
	content := string(data)
	assert.Contains(t, content, "local-zone: \"api.fzymgc.house.\" static\n")
	assert.Contains(t, content, "local-data: \"api.fzymgc.house. 300 IN A 10.0.0.5\"\n")
	assert.Contains(t, content, "local-zone: \"sso.fzymgc.house.\" static\n")
}

func TestUnboundRegenerate_InvalidPath(t *testing.T) {
	ctx := context.Background()

	store, err := sqlite.New(fmt.Sprintf("file:%s?mode=memory&cache=shared", t.Name()), slog.Default())
	require.NoError(t, err)
	require.NoError(t, store.Initialize(ctx))
	t.Cleanup(func() { _ = store.Close() })

	gen := NewUnboundConfGenerator("/nonexistent/dir/router-hosts.conf", 0)
	_, err = gen.Regenerate(ctx, store)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "create temp file")
}

func TestRegenerateOutputs_WritesUnbound(t *testing.T) {
	ctx := context.Background()

	store, err := sqlite.New(fmt.Sprintf("file:%s?mode=memory&cache=shared", t.Name()), slog.Default())
	require.NoError(t, err)
	require.NoError(t, store.Initialize(ctx))
	t.Cleanup(func() { _ = store.Close() })

	handler := NewCommandHandler(store)
	_, err = handler.AddHost(ctx, "10.0.0.5", "api.fzymgc.house", nil, nil, nil)
	require.NoError(t, err)

	dir := t.TempDir()
	path := filepath.Join(dir, "router-hosts.conf")
	svc := NewHostsServiceImpl(handler, store, WithUnboundGenerator(NewUnboundConfGenerator(path, 0)))

	svc.RegenerateOutputs(ctx)

	data, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Contains(t, string(data), "local-zone: \"api.fzymgc.house.\" static\n")
}
