name: 'CI Tools Setup'
description: 'Install Task, cargo-nextest, and cargo-llvm-cov'

runs:
  using: 'composite'
  steps:
    - name: Install Task
      uses: arduino/setup-task@v2

    - name: Install cargo-nextest
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest

    - name: Install cargo-llvm-cov
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-llvm-cov
