// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: router_hosts/v1/hosts.proto

package hostsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostsService_AddHost_FullMethodName            = "/router_hosts.v1.HostsService/AddHost"
	HostsService_GetHost_FullMethodName            = "/router_hosts.v1.HostsService/GetHost"
	HostsService_UpdateHost_FullMethodName         = "/router_hosts.v1.HostsService/UpdateHost"
	HostsService_DeleteHost_FullMethodName         = "/router_hosts.v1.HostsService/DeleteHost"
	HostsService_ListHosts_FullMethodName          = "/router_hosts.v1.HostsService/ListHosts"
	HostsService_SearchHosts_FullMethodName        = "/router_hosts.v1.HostsService/SearchHosts"
	HostsService_ImportHosts_FullMethodName        = "/router_hosts.v1.HostsService/ImportHosts"
	HostsService_ExportHosts_FullMethodName        = "/router_hosts.v1.HostsService/ExportHosts"
	HostsService_CreateSnapshot_FullMethodName     = "/router_hosts.v1.HostsService/CreateSnapshot"
	HostsService_ListSnapshots_FullMethodName      = "/router_hosts.v1.HostsService/ListSnapshots"
	HostsService_RollbackToSnapshot_FullMethodName = "/router_hosts.v1.HostsService/RollbackToSnapshot"
	HostsService_DeleteSnapshot_FullMethodName     = "/router_hosts.v1.HostsService/DeleteSnapshot"
	HostsService_Liveness_FullMethodName           = "/router_hosts.v1.HostsService/Liveness"
	HostsService_Readiness_FullMethodName          = "/router_hosts.v1.HostsService/Readiness"
	HostsService_Health_FullMethodName             = "/router_hosts.v1.HostsService/Health"
)

// HostsServiceClient is the client API for HostsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for managing /etc/hosts entries via gRPC
type HostsServiceClient interface {
	// Add a new host entry to the hosts file
	AddHost(ctx context.Context, in *AddHostRequest, opts ...grpc.CallOption) (*AddHostResponse, error)
	// Retrieve a single host entry by its ID
	GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostResponse, error)
	// Update an existing host entry
	UpdateHost(ctx context.Context, in *UpdateHostRequest, opts ...grpc.CallOption) (*UpdateHostResponse, error)
	// Delete a host entry (creates tombstone event)
	DeleteHost(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostResponse, error)
	// List all host entries with optional filtering and pagination (server streaming)
	ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListHostsResponse], error)
	// Search for host entries by query string (server streaming)
	SearchHosts(ctx context.Context, in *SearchHostsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchHostsResponse], error)
	// Import hosts from a file format via client streaming with server progress updates
	ImportHosts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ImportHostsRequest, ImportHostsResponse], error)
	// Export all hosts in a specified format via server streaming
	ExportHosts(ctx context.Context, in *ExportHostsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportHostsResponse], error)
	// Create a snapshot of the current hosts database state
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	// List all available snapshots (server streaming)
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListSnapshotsResponse], error)
	// Restore the hosts database to a previous snapshot (creates backup snapshot first)
	RollbackToSnapshot(ctx context.Context, in *RollbackToSnapshotRequest, opts ...grpc.CallOption) (*RollbackToSnapshotResponse, error)
	// Delete a snapshot by its ID
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	// Check if the server process is alive (minimal check, no I/O)
	Liveness(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessResponse, error)
	// Check if the server is ready to handle requests (verifies database connectivity)
	Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error)
	// Get detailed health status of all server components
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type hostsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHostsServiceClient(cc grpc.ClientConnInterface) HostsServiceClient {
	return &hostsServiceClient{cc}
}

func (c *hostsServiceClient) AddHost(ctx context.Context, in *AddHostRequest, opts ...grpc.CallOption) (*AddHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddHostResponse)
	err := c.cc.Invoke(ctx, HostsService_AddHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) GetHost(ctx context.Context, in *GetHostRequest, opts ...grpc.CallOption) (*GetHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHostResponse)
	err := c.cc.Invoke(ctx, HostsService_GetHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) UpdateHost(ctx context.Context, in *UpdateHostRequest, opts ...grpc.CallOption) (*UpdateHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHostResponse)
	err := c.cc.Invoke(ctx, HostsService_UpdateHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) DeleteHost(ctx context.Context, in *DeleteHostRequest, opts ...grpc.CallOption) (*DeleteHostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteHostResponse)
	err := c.cc.Invoke(ctx, HostsService_DeleteHost_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) ListHosts(ctx context.Context, in *ListHostsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListHostsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostsService_ServiceDesc.Streams[0], HostsService_ListHosts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListHostsRequest, ListHostsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_ListHostsClient = grpc.ServerStreamingClient[ListHostsResponse]

func (c *hostsServiceClient) SearchHosts(ctx context.Context, in *SearchHostsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchHostsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostsService_ServiceDesc.Streams[1], HostsService_SearchHosts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchHostsRequest, SearchHostsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_SearchHostsClient = grpc.ServerStreamingClient[SearchHostsResponse]

func (c *hostsServiceClient) ImportHosts(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ImportHostsRequest, ImportHostsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostsService_ServiceDesc.Streams[2], HostsService_ImportHosts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportHostsRequest, ImportHostsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_ImportHostsClient = grpc.BidiStreamingClient[ImportHostsRequest, ImportHostsResponse]

func (c *hostsServiceClient) ExportHosts(ctx context.Context, in *ExportHostsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportHostsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostsService_ServiceDesc.Streams[3], HostsService_ExportHosts_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportHostsRequest, ExportHostsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_ExportHostsClient = grpc.ServerStreamingClient[ExportHostsResponse]

func (c *hostsServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, HostsService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ListSnapshotsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HostsService_ServiceDesc.Streams[4], HostsService_ListSnapshots_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListSnapshotsRequest, ListSnapshotsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_ListSnapshotsClient = grpc.ServerStreamingClient[ListSnapshotsResponse]

func (c *hostsServiceClient) RollbackToSnapshot(ctx context.Context, in *RollbackToSnapshotRequest, opts ...grpc.CallOption) (*RollbackToSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackToSnapshotResponse)
	err := c.cc.Invoke(ctx, HostsService_RollbackToSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, HostsService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) Liveness(ctx context.Context, in *LivenessRequest, opts ...grpc.CallOption) (*LivenessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LivenessResponse)
	err := c.cc.Invoke(ctx, HostsService_Liveness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) Readiness(ctx context.Context, in *ReadinessRequest, opts ...grpc.CallOption) (*ReadinessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadinessResponse)
	err := c.cc.Invoke(ctx, HostsService_Readiness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hostsServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, HostsService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostsServiceServer is the server API for HostsService service.
// All implementations must embed UnimplementedHostsServiceServer
// for forward compatibility.
//
// Service definition for managing /etc/hosts entries via gRPC
type HostsServiceServer interface {
	// Add a new host entry to the hosts file
	AddHost(context.Context, *AddHostRequest) (*AddHostResponse, error)
	// Retrieve a single host entry by its ID
	GetHost(context.Context, *GetHostRequest) (*GetHostResponse, error)
	// Update an existing host entry
	UpdateHost(context.Context, *UpdateHostRequest) (*UpdateHostResponse, error)
	// Delete a host entry (creates tombstone event)
	DeleteHost(context.Context, *DeleteHostRequest) (*DeleteHostResponse, error)
	// List all host entries with optional filtering and pagination (server streaming)
	ListHosts(*ListHostsRequest, grpc.ServerStreamingServer[ListHostsResponse]) error
	// Search for host entries by query string (server streaming)
	SearchHosts(*SearchHostsRequest, grpc.ServerStreamingServer[SearchHostsResponse]) error
	// Import hosts from a file format via client streaming with server progress updates
	ImportHosts(grpc.BidiStreamingServer[ImportHostsRequest, ImportHostsResponse]) error
	// Export all hosts in a specified format via server streaming
	ExportHosts(*ExportHostsRequest, grpc.ServerStreamingServer[ExportHostsResponse]) error
	// Create a snapshot of the current hosts database state
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	// List all available snapshots (server streaming)
	ListSnapshots(*ListSnapshotsRequest, grpc.ServerStreamingServer[ListSnapshotsResponse]) error
	// Restore the hosts database to a previous snapshot (creates backup snapshot first)
	RollbackToSnapshot(context.Context, *RollbackToSnapshotRequest) (*RollbackToSnapshotResponse, error)
	// Delete a snapshot by its ID
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	// Check if the server process is alive (minimal check, no I/O)
	Liveness(context.Context, *LivenessRequest) (*LivenessResponse, error)
	// Check if the server is ready to handle requests (verifies database connectivity)
	Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error)
	// Get detailed health status of all server components
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedHostsServiceServer()
}

// UnimplementedHostsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostsServiceServer struct{}

func (UnimplementedHostsServiceServer) AddHost(context.Context, *AddHostRequest) (*AddHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddHost not implemented")
}
func (UnimplementedHostsServiceServer) GetHost(context.Context, *GetHostRequest) (*GetHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHost not implemented")
}
func (UnimplementedHostsServiceServer) UpdateHost(context.Context, *UpdateHostRequest) (*UpdateHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHost not implemented")
}
func (UnimplementedHostsServiceServer) DeleteHost(context.Context, *DeleteHostRequest) (*DeleteHostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteHost not implemented")
}
func (UnimplementedHostsServiceServer) ListHosts(*ListHostsRequest, grpc.ServerStreamingServer[ListHostsResponse]) error {
	return status.Error(codes.Unimplemented, "method ListHosts not implemented")
}
func (UnimplementedHostsServiceServer) SearchHosts(*SearchHostsRequest, grpc.ServerStreamingServer[SearchHostsResponse]) error {
	return status.Error(codes.Unimplemented, "method SearchHosts not implemented")
}
func (UnimplementedHostsServiceServer) ImportHosts(grpc.BidiStreamingServer[ImportHostsRequest, ImportHostsResponse]) error {
	return status.Error(codes.Unimplemented, "method ImportHosts not implemented")
}
func (UnimplementedHostsServiceServer) ExportHosts(*ExportHostsRequest, grpc.ServerStreamingServer[ExportHostsResponse]) error {
	return status.Error(codes.Unimplemented, "method ExportHosts not implemented")
}
func (UnimplementedHostsServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedHostsServiceServer) ListSnapshots(*ListSnapshotsRequest, grpc.ServerStreamingServer[ListSnapshotsResponse]) error {
	return status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedHostsServiceServer) RollbackToSnapshot(context.Context, *RollbackToSnapshotRequest) (*RollbackToSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackToSnapshot not implemented")
}
func (UnimplementedHostsServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedHostsServiceServer) Liveness(context.Context, *LivenessRequest) (*LivenessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Liveness not implemented")
}
func (UnimplementedHostsServiceServer) Readiness(context.Context, *ReadinessRequest) (*ReadinessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Readiness not implemented")
}
func (UnimplementedHostsServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedHostsServiceServer) mustEmbedUnimplementedHostsServiceServer() {}
func (UnimplementedHostsServiceServer) testEmbeddedByValue()                      {}

// UnsafeHostsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostsServiceServer will
// result in compilation errors.
type UnsafeHostsServiceServer interface {
	mustEmbedUnimplementedHostsServiceServer()
}

func RegisterHostsServiceServer(s grpc.ServiceRegistrar, srv HostsServiceServer) {
	// If the following call panics, it indicates UnimplementedHostsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostsService_ServiceDesc, srv)
}

func _HostsService_AddHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).AddHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_AddHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).AddHost(ctx, req.(*AddHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_GetHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).GetHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_GetHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).GetHost(ctx, req.(*GetHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_UpdateHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).UpdateHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_UpdateHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).UpdateHost(ctx, req.(*UpdateHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_DeleteHost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).DeleteHost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_DeleteHost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).DeleteHost(ctx, req.(*DeleteHostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_ListHosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListHostsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostsServiceServer).ListHosts(m, &grpc.GenericServerStream[ListHostsRequest, ListHostsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_ListHostsServer = grpc.ServerStreamingServer[ListHostsResponse]

func _HostsService_SearchHosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchHostsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostsServiceServer).SearchHosts(m, &grpc.GenericServerStream[SearchHostsRequest, SearchHostsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_SearchHostsServer = grpc.ServerStreamingServer[SearchHostsResponse]

func _HostsService_ImportHosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HostsServiceServer).ImportHosts(&grpc.GenericServerStream[ImportHostsRequest, ImportHostsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_ImportHostsServer = grpc.BidiStreamingServer[ImportHostsRequest, ImportHostsResponse]

func _HostsService_ExportHosts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportHostsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostsServiceServer).ExportHosts(m, &grpc.GenericServerStream[ExportHostsRequest, ExportHostsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_ExportHostsServer = grpc.ServerStreamingServer[ExportHostsResponse]

func _HostsService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_ListSnapshots_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListSnapshotsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HostsServiceServer).ListSnapshots(m, &grpc.GenericServerStream[ListSnapshotsRequest, ListSnapshotsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HostsService_ListSnapshotsServer = grpc.ServerStreamingServer[ListSnapshotsResponse]

func _HostsService_RollbackToSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackToSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).RollbackToSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_RollbackToSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).RollbackToSnapshot(ctx, req.(*RollbackToSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_Liveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LivenessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).Liveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_Liveness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).Liveness(ctx, req.(*LivenessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_Readiness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadinessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).Readiness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_Readiness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).Readiness(ctx, req.(*ReadinessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HostsService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostsServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostsService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostsServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostsService_ServiceDesc is the grpc.ServiceDesc for HostsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "router_hosts.v1.HostsService",
	HandlerType: (*HostsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddHost",
			Handler:    _HostsService_AddHost_Handler,
		},
		{
			MethodName: "GetHost",
			Handler:    _HostsService_GetHost_Handler,
		},
		{
			MethodName: "UpdateHost",
			Handler:    _HostsService_UpdateHost_Handler,
		},
		{
			MethodName: "DeleteHost",
			Handler:    _HostsService_DeleteHost_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _HostsService_CreateSnapshot_Handler,
		},
		{
			MethodName: "RollbackToSnapshot",
			Handler:    _HostsService_RollbackToSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _HostsService_DeleteSnapshot_Handler,
		},
		{
			MethodName: "Liveness",
			Handler:    _HostsService_Liveness_Handler,
		},
		{
			MethodName: "Readiness",
			Handler:    _HostsService_Readiness_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _HostsService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListHosts",
			Handler:       _HostsService_ListHosts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchHosts",
			Handler:       _HostsService_SearchHosts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImportHosts",
			Handler:       _HostsService_ImportHosts_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ExportHosts",
			Handler:       _HostsService_ExportHosts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListSnapshots",
			Handler:       _HostsService_ListSnapshots_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "router_hosts/v1/hosts.proto",
}
