// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: router_hosts/v1/hosts.proto

package hostsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a single host entry in the hosts file
type HostEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this host entry (ULID format)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// IP address (IPv4 or IPv6) for the host
	IpAddress string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// DNS hostname or FQDN for the host
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Optional comment to appear in hosts file
	Comment *string `protobuf:"bytes,4,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	// Optional tags for categorization and filtering (e.g., "homelab", "production")
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// Timestamp when this entry was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Timestamp when this entry was last updated
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// Version identifier for optimistic concurrency control.
	// Treat as opaque - compare for equality only, do not parse.
	// Format may change in future versions.
	Version string `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	// Optional hostname aliases (additional names resolving to same IP)
	Aliases       []string `protobuf:"bytes,9,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HostEntry) Reset() {
	*x = HostEntry{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HostEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostEntry) ProtoMessage() {}

func (x *HostEntry) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostEntry.ProtoReflect.Descriptor instead.
func (*HostEntry) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{0}
}

func (x *HostEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HostEntry) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *HostEntry) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostEntry) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *HostEntry) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *HostEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *HostEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *HostEntry) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HostEntry) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

// Wrapper for updating aliases with optional semantics
type AliasesUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New alias values (empty array = clear all aliases)
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AliasesUpdate) Reset() {
	*x = AliasesUpdate{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AliasesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AliasesUpdate) ProtoMessage() {}

func (x *AliasesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AliasesUpdate.ProtoReflect.Descriptor instead.
func (*AliasesUpdate) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{1}
}

func (x *AliasesUpdate) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Wrapper for updating tags with optional semantics
type TagsUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// New tag values (empty array = clear all tags)
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsUpdate) Reset() {
	*x = TagsUpdate{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsUpdate) ProtoMessage() {}

func (x *TagsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsUpdate.ProtoReflect.Descriptor instead.
func (*TagsUpdate) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{2}
}

func (x *TagsUpdate) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Request to add a new host entry
type AddHostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// IP address (IPv4 or IPv6) for the new host (required)
	IpAddress string `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	// DNS hostname for the new host (required)
	Hostname string `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// Optional comment for the host entry
	Comment *string `protobuf:"bytes,3,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	// Optional tags for categorization
	Tags []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	// Optional hostname aliases
	Aliases       []string `protobuf:"bytes,5,rep,name=aliases,proto3" json:"aliases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHostRequest) Reset() {
	*x = AddHostRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHostRequest) ProtoMessage() {}

func (x *AddHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHostRequest.ProtoReflect.Descriptor instead.
func (*AddHostRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{3}
}

func (x *AddHostRequest) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *AddHostRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AddHostRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *AddHostRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddHostRequest) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

// Response after adding a host entry
type AddHostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the newly created host entry
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The complete host entry that was created
	Entry         *HostEntry `protobuf:"bytes,2,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHostResponse) Reset() {
	*x = AddHostResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHostResponse) ProtoMessage() {}

func (x *AddHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHostResponse.ProtoReflect.Descriptor instead.
func (*AddHostResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{4}
}

func (x *AddHostResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddHostResponse) GetEntry() *HostEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Request to retrieve a single host entry by ID
type GetHostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the host entry to retrieve
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostRequest) Reset() {
	*x = GetHostRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostRequest) ProtoMessage() {}

func (x *GetHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostRequest.ProtoReflect.Descriptor instead.
func (*GetHostRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{5}
}

func (x *GetHostRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response containing the requested host entry
type GetHostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The requested host entry
	Entry         *HostEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHostResponse) Reset() {
	*x = GetHostResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHostResponse) ProtoMessage() {}

func (x *GetHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHostResponse.ProtoReflect.Descriptor instead.
func (*GetHostResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{6}
}

func (x *GetHostResponse) GetEntry() *HostEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Request to update an existing host entry
type UpdateHostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the host entry to update (required)
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// New IP address (optional, keeps existing if not provided)
	IpAddress *string `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3,oneof" json:"ip_address,omitempty"`
	// New hostname (optional, keeps existing if not provided)
	Hostname *string `protobuf:"bytes,3,opt,name=hostname,proto3,oneof" json:"hostname,omitempty"`
	// New comment (optional, keeps existing if not provided, empty string to clear)
	Comment *string `protobuf:"bytes,4,opt,name=comment,proto3,oneof" json:"comment,omitempty"`
	// Expected version for optimistic concurrency control
	ExpectedVersion *string `protobuf:"bytes,6,opt,name=expected_version,json=expectedVersion,proto3,oneof" json:"expected_version,omitempty"`
	// New aliases (wrapper for optional semantics)
	Aliases *AliasesUpdate `protobuf:"bytes,7,opt,name=aliases,proto3" json:"aliases,omitempty"`
	// New tags (wrapper for optional semantics - breaking change from field 5)
	Tags          *TagsUpdate `protobuf:"bytes,8,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHostRequest) Reset() {
	*x = UpdateHostRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostRequest) ProtoMessage() {}

func (x *UpdateHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostRequest.ProtoReflect.Descriptor instead.
func (*UpdateHostRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateHostRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateHostRequest) GetIpAddress() string {
	if x != nil && x.IpAddress != nil {
		return *x.IpAddress
	}
	return ""
}

func (x *UpdateHostRequest) GetHostname() string {
	if x != nil && x.Hostname != nil {
		return *x.Hostname
	}
	return ""
}

func (x *UpdateHostRequest) GetComment() string {
	if x != nil && x.Comment != nil {
		return *x.Comment
	}
	return ""
}

func (x *UpdateHostRequest) GetExpectedVersion() string {
	if x != nil && x.ExpectedVersion != nil {
		return *x.ExpectedVersion
	}
	return ""
}

func (x *UpdateHostRequest) GetAliases() *AliasesUpdate {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *UpdateHostRequest) GetTags() *TagsUpdate {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Response after updating a host entry
type UpdateHostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated host entry with new values
	Entry         *HostEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateHostResponse) Reset() {
	*x = UpdateHostResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateHostResponse) ProtoMessage() {}

func (x *UpdateHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateHostResponse.ProtoReflect.Descriptor instead.
func (*UpdateHostResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateHostResponse) GetEntry() *HostEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Request to delete a host entry (creates tombstone event)
type DeleteHostRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the host entry to delete
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHostRequest) Reset() {
	*x = DeleteHostRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostRequest) ProtoMessage() {}

func (x *DeleteHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostRequest.ProtoReflect.Descriptor instead.
func (*DeleteHostRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteHostRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response after deleting a host entry
type DeleteHostResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deletion succeeded
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteHostResponse) Reset() {
	*x = DeleteHostResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteHostResponse) ProtoMessage() {}

func (x *DeleteHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteHostResponse.ProtoReflect.Descriptor instead.
func (*DeleteHostResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteHostResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request to list host entries with optional filtering and pagination
type ListHostsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter expression (e.g., by tag, active status)
	Filter *string `protobuf:"bytes,1,opt,name=filter,proto3,oneof" json:"filter,omitempty"`
	// Maximum number of entries to return (pagination)
	Limit *int32 `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	// Number of entries to skip (pagination)
	Offset        *int32 `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsRequest) Reset() {
	*x = ListHostsRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsRequest) ProtoMessage() {}

func (x *ListHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsRequest.ProtoReflect.Descriptor instead.
func (*ListHostsRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{11}
}

func (x *ListHostsRequest) GetFilter() string {
	if x != nil && x.Filter != nil {
		return *x.Filter
	}
	return ""
}

func (x *ListHostsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListHostsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

// Response containing a single host entry (streamed)
type ListHostsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A host entry from the list
	Entry         *HostEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHostsResponse) Reset() {
	*x = ListHostsResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHostsResponse) ProtoMessage() {}

func (x *ListHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHostsResponse.ProtoReflect.Descriptor instead.
func (*ListHostsResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{12}
}

func (x *ListHostsResponse) GetEntry() *HostEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Request to search for host entries by query
type SearchHostsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Search query (searches IP, hostname, comment, and tags)
	Query         string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHostsRequest) Reset() {
	*x = SearchHostsRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHostsRequest) ProtoMessage() {}

func (x *SearchHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHostsRequest.ProtoReflect.Descriptor instead.
func (*SearchHostsRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{13}
}

func (x *SearchHostsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

// Response containing a single matching host entry (streamed)
type SearchHostsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A host entry that matches the search query
	Entry         *HostEntry `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHostsResponse) Reset() {
	*x = SearchHostsResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHostsResponse) ProtoMessage() {}

func (x *SearchHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHostsResponse.ProtoReflect.Descriptor instead.
func (*SearchHostsResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{14}
}

func (x *SearchHostsResponse) GetEntry() *HostEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

// Request to import hosts from a file format via streaming chunks
type ImportHostsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk of file data being uploaded
	Chunk []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	// Whether this is the final chunk of the import
	LastChunk bool `protobuf:"varint,2,opt,name=last_chunk,json=lastChunk,proto3" json:"last_chunk,omitempty"`
	// Import format: "hosts" (default), "json", "csv"
	Format *string `protobuf:"bytes,3,opt,name=format,proto3,oneof" json:"format,omitempty"`
	// Conflict handling: "skip" (default), "replace", "strict"
	ConflictMode *string `protobuf:"bytes,4,opt,name=conflict_mode,json=conflictMode,proto3,oneof" json:"conflict_mode,omitempty"`
	// Override strict mode validation (e.g., alias conflicts with existing hostname)
	Force         *bool `protobuf:"varint,5,opt,name=force,proto3,oneof" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportHostsRequest) Reset() {
	*x = ImportHostsRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportHostsRequest) ProtoMessage() {}

func (x *ImportHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportHostsRequest.ProtoReflect.Descriptor instead.
func (*ImportHostsRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{15}
}

func (x *ImportHostsRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *ImportHostsRequest) GetLastChunk() bool {
	if x != nil {
		return x.LastChunk
	}
	return false
}

func (x *ImportHostsRequest) GetFormat() string {
	if x != nil && x.Format != nil {
		return *x.Format
	}
	return ""
}

func (x *ImportHostsRequest) GetConflictMode() string {
	if x != nil && x.ConflictMode != nil {
		return *x.ConflictMode
	}
	return ""
}

func (x *ImportHostsRequest) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

// Response for host import operation (streamed progress updates)
//
// Example counter values for importing 5 entries where 2 already exist:
//
// With conflict_mode = "skip":
//
//	processed=5, created=3, updated=0, skipped=2, failed=0
//	(existing entries left unchanged, counted as skipped)
//
// With conflict_mode = "replace":
//
//	processed=5, created=3, updated=2, skipped=0, failed=0
//	(existing entries updated with new values)
//
// Example with validation failures (2 invalid entries):
//
//	processed=5, created=2, updated=0, skipped=0, failed=3
//	validation_errors=["Line 1: Invalid IP '999.0.0.1': ...",
//	                   "Line 3: Invalid hostname 'bad_host': ...",
//	                   "Line 5: Invalid IP 'not-an-ip': ..."]
//
// Note: In replace mode, if existing entry has identical values, it counts
// as skipped (no-op), not updated.
type ImportHostsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total entries processed so far
	Processed int32 `protobuf:"varint,1,opt,name=processed,proto3" json:"processed,omitempty"`
	// Successfully created entries
	Created int32 `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	// Existing entries updated. Only non-zero when conflict_mode = "replace".
	// In skip mode, duplicates increment skipped instead.
	Updated int32 `protobuf:"varint,3,opt,name=updated,proto3" json:"updated,omitempty"`
	// Duplicates skipped (when conflict_mode = "skip")
	Skipped int32 `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	// Validation failures
	Failed int32 `protobuf:"varint,5,opt,name=failed,proto3" json:"failed,omitempty"`
	// Error message if import operation encountered an issue
	Error *string `protobuf:"bytes,6,opt,name=error,proto3,oneof" json:"error,omitempty"`
	// Details of validation failures (line number and reason)
	// Only populated when failed > 0
	ValidationErrors []string `protobuf:"bytes,7,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ImportHostsResponse) Reset() {
	*x = ImportHostsResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportHostsResponse) ProtoMessage() {}

func (x *ImportHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportHostsResponse.ProtoReflect.Descriptor instead.
func (*ImportHostsResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{16}
}

func (x *ImportHostsResponse) GetProcessed() int32 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *ImportHostsResponse) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ImportHostsResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *ImportHostsResponse) GetSkipped() int32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

func (x *ImportHostsResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *ImportHostsResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *ImportHostsResponse) GetValidationErrors() []string {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

// Request to export all hosts in a specified format
type ExportHostsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Export format: "hosts" (standard /etc/hosts), "json", or "csv"
	Format        string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportHostsRequest) Reset() {
	*x = ExportHostsRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportHostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportHostsRequest) ProtoMessage() {}

func (x *ExportHostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportHostsRequest.ProtoReflect.Descriptor instead.
func (*ExportHostsRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{17}
}

func (x *ExportHostsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Response containing exported host data (streamed in chunks)
type ExportHostsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Chunk of exported data in the requested format
	Chunk         []byte `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportHostsResponse) Reset() {
	*x = ExportHostsResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportHostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportHostsResponse) ProtoMessage() {}

func (x *ExportHostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportHostsResponse.ProtoReflect.Descriptor instead.
func (*ExportHostsResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{18}
}

func (x *ExportHostsResponse) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

// Request to create a snapshot of the current hosts database state
type CreateSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional name for the snapshot (auto-generated if not provided)
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// What triggered this snapshot (defaults to "manual" if not provided)
	Trigger       string `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{19}
}

func (x *CreateSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSnapshotRequest) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

// Response after creating a snapshot
type CreateSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the newly created snapshot
	SnapshotId string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// Timestamp when snapshot was created (microseconds since epoch)
	CreatedAt int64 `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Number of entries in the snapshot
	EntryCount    int32 `protobuf:"varint,3,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{20}
}

func (x *CreateSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CreateSnapshotResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CreateSnapshotResponse) GetEntryCount() int32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

// Represents a saved snapshot of the hosts database at a point in time
type Snapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this snapshot
	SnapshotId string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	// Timestamp when this snapshot was created
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Number of host entries captured in this snapshot
	EntryCount int32 `protobuf:"varint,3,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	// What triggered this snapshot (e.g., "manual", "pre-rollback", "scheduled")
	Trigger string `protobuf:"bytes,4,opt,name=trigger,proto3" json:"trigger,omitempty"`
	// Optional snapshot name
	Name          string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{21}
}

func (x *Snapshot) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *Snapshot) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Snapshot) GetEntryCount() int32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *Snapshot) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

func (x *Snapshot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Request to list all available snapshots
type ListSnapshotsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional limit for pagination
	Limit uint32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	// Optional offset for pagination
	Offset        uint32 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{22}
}

func (x *ListSnapshotsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSnapshotsRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response containing a single snapshot (streamed)
type ListSnapshotsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A snapshot from the list
	Snapshot      *Snapshot `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{23}
}

func (x *ListSnapshotsResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// Request to restore the hosts database to a previous snapshot state
type RollbackToSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the snapshot to restore
	SnapshotId    string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackToSnapshotRequest) Reset() {
	*x = RollbackToSnapshotRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackToSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackToSnapshotRequest) ProtoMessage() {}

func (x *RollbackToSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackToSnapshotRequest.ProtoReflect.Descriptor instead.
func (*RollbackToSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{24}
}

func (x *RollbackToSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

// Response after rolling back to a snapshot
type RollbackToSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the rollback succeeded
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// ID of the auto-created snapshot taken before rollback (for undo capability)
	NewSnapshotId string `protobuf:"bytes,2,opt,name=new_snapshot_id,json=newSnapshotId,proto3" json:"new_snapshot_id,omitempty"`
	// Number of host entries restored from the snapshot
	RestoredEntryCount int32 `protobuf:"varint,3,opt,name=restored_entry_count,json=restoredEntryCount,proto3" json:"restored_entry_count,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RollbackToSnapshotResponse) Reset() {
	*x = RollbackToSnapshotResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackToSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackToSnapshotResponse) ProtoMessage() {}

func (x *RollbackToSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackToSnapshotResponse.ProtoReflect.Descriptor instead.
func (*RollbackToSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{25}
}

func (x *RollbackToSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RollbackToSnapshotResponse) GetNewSnapshotId() string {
	if x != nil {
		return x.NewSnapshotId
	}
	return ""
}

func (x *RollbackToSnapshotResponse) GetRestoredEntryCount() int32 {
	if x != nil {
		return x.RestoredEntryCount
	}
	return 0
}

// Request to delete a snapshot
type DeleteSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the snapshot to delete
	SnapshotId    string `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

// Response after deleting a snapshot
type DeleteSnapshotResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deletion succeeded
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Request for liveness check (is the process alive?)
type LivenessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessRequest) Reset() {
	*x = LivenessRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessRequest) ProtoMessage() {}

func (x *LivenessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessRequest.ProtoReflect.Descriptor instead.
func (*LivenessRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{28}
}

// Response for liveness check
type LivenessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Always true if the server can respond
	Alive         bool `protobuf:"varint,1,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LivenessResponse) Reset() {
	*x = LivenessResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LivenessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LivenessResponse) ProtoMessage() {}

func (x *LivenessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LivenessResponse.ProtoReflect.Descriptor instead.
func (*LivenessResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{29}
}

func (x *LivenessResponse) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

// Request for readiness check (is the server ready to handle requests?)
type ReadinessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessRequest) Reset() {
	*x = ReadinessRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessRequest) ProtoMessage() {}

func (x *ReadinessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessRequest.ProtoReflect.Descriptor instead.
func (*ReadinessRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{30}
}

// Response for readiness check
type ReadinessResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the server is ready to handle requests
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Reason for not being ready (empty if ready)
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadinessResponse) Reset() {
	*x = ReadinessResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadinessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadinessResponse) ProtoMessage() {}

func (x *ReadinessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadinessResponse.ProtoReflect.Descriptor instead.
func (*ReadinessResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{31}
}

func (x *ReadinessResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadinessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Request for detailed health status
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{32}
}

// Response containing detailed health status of all components
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Overall health status (true if all critical components are healthy)
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Server information
	Server *ServerInfo `protobuf:"bytes,2,opt,name=server,proto3" json:"server,omitempty"`
	// Database health status
	Database *DatabaseHealth `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	// ACME certificate health status
	Acme *AcmeHealth `protobuf:"bytes,4,opt,name=acme,proto3" json:"acme,omitempty"`
	// Hooks configuration status
	Hooks         *HooksHealth `protobuf:"bytes,5,opt,name=hooks,proto3" json:"hooks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{33}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetServer() *ServerInfo {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *HealthResponse) GetDatabase() *DatabaseHealth {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *HealthResponse) GetAcme() *AcmeHealth {
	if x != nil {
		return x.Acme
	}
	return nil
}

func (x *HealthResponse) GetHooks() *HooksHealth {
	if x != nil {
		return x.Hooks
	}
	return nil
}

// Server information and metadata
type ServerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server version (e.g., "0.6.0")
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Server uptime in seconds
	UptimeSeconds int64 `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Build information (e.g., "v0.6.0 (abc1234)")
	BuildInfo     string `protobuf:"bytes,3,opt,name=build_info,json=buildInfo,proto3" json:"build_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{34}
}

func (x *ServerInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfo) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *ServerInfo) GetBuildInfo() string {
	if x != nil {
		return x.BuildInfo
	}
	return ""
}

// Database health status
type DatabaseHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the database connection is working
	Connected bool `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	// Database backend type: "sqlite", "postgresql", "duckdb"
	Backend string `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	// Last health check latency in milliseconds
	LatencyMs int64 `protobuf:"varint,3,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Error message if not connected (empty if healthy)
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatabaseHealth) Reset() {
	*x = DatabaseHealth{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseHealth) ProtoMessage() {}

func (x *DatabaseHealth) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatabaseHealth.ProtoReflect.Descriptor instead.
func (*DatabaseHealth) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{35}
}

func (x *DatabaseHealth) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *DatabaseHealth) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

func (x *DatabaseHealth) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DatabaseHealth) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ACME certificate health status
type AcmeHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether ACME is enabled
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Certificate status: "valid", "renewing", "expired", "disabled"
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Certificate expiry timestamp (Unix seconds, 0 if disabled)
	ExpiresAt int64 `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// Error message if there's an issue (empty if healthy)
	Error         string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcmeHealth) Reset() {
	*x = AcmeHealth{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcmeHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcmeHealth) ProtoMessage() {}

func (x *AcmeHealth) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcmeHealth.ProtoReflect.Descriptor instead.
func (*AcmeHealth) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{36}
}

func (x *AcmeHealth) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AcmeHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AcmeHealth) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *AcmeHealth) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Hooks configuration status
type HooksHealth struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of configured hooks
	ConfiguredCount int32 `protobuf:"varint,1,opt,name=configured_count,json=configuredCount,proto3" json:"configured_count,omitempty"`
	// Names of configured hooks
	HookNames     []string `protobuf:"bytes,2,rep,name=hook_names,json=hookNames,proto3" json:"hook_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HooksHealth) Reset() {
	*x = HooksHealth{}
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HooksHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HooksHealth) ProtoMessage() {}

func (x *HooksHealth) ProtoReflect() protoreflect.Message {
	mi := &file_router_hosts_v1_hosts_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HooksHealth.ProtoReflect.Descriptor instead.
func (*HooksHealth) Descriptor() ([]byte, []int) {
	return file_router_hosts_v1_hosts_proto_rawDescGZIP(), []int{37}
}

func (x *HooksHealth) GetConfiguredCount() int32 {
	if x != nil {
		return x.ConfiguredCount
	}
	return 0
}

func (x *HooksHealth) GetHookNames() []string {
	if x != nil {
		return x.HookNames
	}
	return nil
}

var File_router_hosts_v1_hosts_proto protoreflect.FileDescriptor

const file_router_hosts_v1_hosts_proto_rawDesc = "" +
	"\n" +
	"\x1brouter_hosts/v1/hosts.proto\x12\x0frouter_hosts.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbf\x02\n" +
	"\tHostEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1d\n" +
	"\acomment\x18\x04 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12\x18\n" +
	"\aaliases\x18\t \x03(\tR\aaliasesB\n" +
	"\n" +
	"\b_comment\"'\n" +
	"\rAliasesUpdate\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"$\n" +
	"\n" +
	"TagsUpdate\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xa4\x01\n" +
	"\x0eAddHostRequest\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x01 \x01(\tR\tipAddress\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x1d\n" +
	"\acomment\x18\x03 \x01(\tH\x00R\acomment\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x18\n" +
	"\aaliases\x18\x05 \x03(\tR\aaliasesB\n" +
	"\n" +
	"\b_comment\"S\n" +
	"\x0fAddHostResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x05entry\x18\x02 \x01(\v2\x1a.router_hosts.v1.HostEntryR\x05entry\" \n" +
	"\x0eGetHostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"C\n" +
	"\x0fGetHostResponse\x120\n" +
	"\x05entry\x18\x01 \x01(\v2\x1a.router_hosts.v1.HostEntryR\x05entry\"\xe5\x02\n" +
	"\x11UpdateHostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\tH\x00R\tipAddress\x88\x01\x01\x12\x1f\n" +
	"\bhostname\x18\x03 \x01(\tH\x01R\bhostname\x88\x01\x01\x12\x1d\n" +
	"\acomment\x18\x04 \x01(\tH\x02R\acomment\x88\x01\x01\x12.\n" +
	"\x10expected_version\x18\x06 \x01(\tH\x03R\x0fexpectedVersion\x88\x01\x01\x128\n" +
	"\aaliases\x18\a \x01(\v2\x1e.router_hosts.v1.AliasesUpdateR\aaliases\x12/\n" +
	"\x04tags\x18\b \x01(\v2\x1b.router_hosts.v1.TagsUpdateR\x04tagsB\r\n" +
	"\v_ip_addressB\v\n" +
	"\t_hostnameB\n" +
	"\n" +
	"\b_commentB\x13\n" +
	"\x11_expected_versionJ\x04\b\x05\x10\x06\"F\n" +
	"\x12UpdateHostResponse\x120\n" +
	"\x05entry\x18\x01 \x01(\v2\x1a.router_hosts.v1.HostEntryR\x05entry\"#\n" +
	"\x11DeleteHostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteHostResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x87\x01\n" +
	"\x10ListHostsRequest\x12\x1b\n" +
	"\x06filter\x18\x01 \x01(\tH\x00R\x06filter\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\x05H\x01R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\x05H\x02R\x06offset\x88\x01\x01B\t\n" +
	"\a_filterB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"E\n" +
	"\x11ListHostsResponse\x120\n" +
	"\x05entry\x18\x01 \x01(\v2\x1a.router_hosts.v1.HostEntryR\x05entry\"*\n" +
	"\x12SearchHostsRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"G\n" +
	"\x13SearchHostsResponse\x120\n" +
	"\x05entry\x18\x01 \x01(\v2\x1a.router_hosts.v1.HostEntryR\x05entry\"\xd2\x01\n" +
	"\x12ImportHostsRequest\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x12\x1d\n" +
	"\n" +
	"last_chunk\x18\x02 \x01(\bR\tlastChunk\x12\x1b\n" +
	"\x06format\x18\x03 \x01(\tH\x00R\x06format\x88\x01\x01\x12(\n" +
	"\rconflict_mode\x18\x04 \x01(\tH\x01R\fconflictMode\x88\x01\x01\x12\x19\n" +
	"\x05force\x18\x05 \x01(\bH\x02R\x05force\x88\x01\x01B\t\n" +
	"\a_formatB\x10\n" +
	"\x0e_conflict_modeB\b\n" +
	"\x06_force\"\xeb\x01\n" +
	"\x13ImportHostsResponse\x12\x1c\n" +
	"\tprocessed\x18\x01 \x01(\x05R\tprocessed\x12\x18\n" +
	"\acreated\x18\x02 \x01(\x05R\acreated\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\x05R\aupdated\x12\x18\n" +
	"\askipped\x18\x04 \x01(\x05R\askipped\x12\x16\n" +
	"\x06failed\x18\x05 \x01(\x05R\x06failed\x12\x19\n" +
	"\x05error\x18\x06 \x01(\tH\x00R\x05error\x88\x01\x01\x12+\n" +
	"\x11validation_errors\x18\a \x03(\tR\x10validationErrorsB\b\n" +
	"\x06_error\",\n" +
	"\x12ExportHostsRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\"+\n" +
	"\x13ExportHostsResponse\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\"E\n" +
	"\x15CreateSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\atrigger\x18\x02 \x01(\tR\atrigger\"y\n" +
	"\x16CreateSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\ventry_count\x18\x03 \x01(\x05R\n" +
	"entryCount\"\xb5\x01\n" +
	"\bSnapshot\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\ventry_count\x18\x03 \x01(\x05R\n" +
	"entryCount\x12\x18\n" +
	"\atrigger\x18\x04 \x01(\tR\atrigger\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\"D\n" +
	"\x14ListSnapshotsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\"N\n" +
	"\x15ListSnapshotsResponse\x125\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x19.router_hosts.v1.SnapshotR\bsnapshot\"<\n" +
	"\x19RollbackToSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"\x90\x01\n" +
	"\x1aRollbackToSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x0fnew_snapshot_id\x18\x02 \x01(\tR\rnewSnapshotId\x120\n" +
	"\x14restored_entry_count\x18\x03 \x01(\x05R\x12restoredEntryCount\"8\n" +
	"\x15DeleteSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"2\n" +
	"\x16DeleteSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x11\n" +
	"\x0fLivenessRequest\"(\n" +
	"\x10LivenessResponse\x12\x14\n" +
	"\x05alive\x18\x01 \x01(\bR\x05alive\"\x12\n" +
	"\x10ReadinessRequest\"A\n" +
	"\x11ReadinessResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x0f\n" +
	"\rHealthRequest\"\x81\x02\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x123\n" +
	"\x06server\x18\x02 \x01(\v2\x1b.router_hosts.v1.ServerInfoR\x06server\x12;\n" +
	"\bdatabase\x18\x03 \x01(\v2\x1f.router_hosts.v1.DatabaseHealthR\bdatabase\x12/\n" +
	"\x04acme\x18\x04 \x01(\v2\x1b.router_hosts.v1.AcmeHealthR\x04acme\x122\n" +
	"\x05hooks\x18\x05 \x01(\v2\x1c.router_hosts.v1.HooksHealthR\x05hooks\"l\n" +
	"\n" +
	"ServerInfo\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12\x1d\n" +
	"\n" +
	"build_info\x18\x03 \x01(\tR\tbuildInfo\"}\n" +
	"\x0eDatabaseHealth\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x18\n" +
	"\abackend\x18\x02 \x01(\tR\abackend\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x03 \x01(\x03R\tlatencyMs\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"s\n" +
	"\n" +
	"AcmeHealth\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"W\n" +
	"\vHooksHealth\x12)\n" +
	"\x10configured_count\x18\x01 \x01(\x05R\x0fconfiguredCount\x12\x1d\n" +
	"\n" +
	"hook_names\x18\x02 \x03(\tR\thookNames2\xcb\n" +
	"\n" +
	"\fHostsService\x12L\n" +
	"\aAddHost\x12\x1f.router_hosts.v1.AddHostRequest\x1a .router_hosts.v1.AddHostResponse\x12L\n" +
	"\aGetHost\x12\x1f.router_hosts.v1.GetHostRequest\x1a .router_hosts.v1.GetHostResponse\x12U\n" +
	"\n" +
	"UpdateHost\x12\".router_hosts.v1.UpdateHostRequest\x1a#.router_hosts.v1.UpdateHostResponse\x12U\n" +
	"\n" +
	"DeleteHost\x12\".router_hosts.v1.DeleteHostRequest\x1a#.router_hosts.v1.DeleteHostResponse\x12T\n" +
	"\tListHosts\x12!.router_hosts.v1.ListHostsRequest\x1a\".router_hosts.v1.ListHostsResponse0\x01\x12Z\n" +
	"\vSearchHosts\x12#.router_hosts.v1.SearchHostsRequest\x1a$.router_hosts.v1.SearchHostsResponse0\x01\x12\\\n" +
	"\vImportHosts\x12#.router_hosts.v1.ImportHostsRequest\x1a$.router_hosts.v1.ImportHostsResponse(\x010\x01\x12Z\n" +
	"\vExportHosts\x12#.router_hosts.v1.ExportHostsRequest\x1a$.router_hosts.v1.ExportHostsResponse0\x01\x12a\n" +
	"\x0eCreateSnapshot\x12&.router_hosts.v1.CreateSnapshotRequest\x1a'.router_hosts.v1.CreateSnapshotResponse\x12`\n" +
	"\rListSnapshots\x12%.router_hosts.v1.ListSnapshotsRequest\x1a&.router_hosts.v1.ListSnapshotsResponse0\x01\x12m\n" +
	"\x12RollbackToSnapshot\x12*.router_hosts.v1.RollbackToSnapshotRequest\x1a+.router_hosts.v1.RollbackToSnapshotResponse\x12a\n" +
	"\x0eDeleteSnapshot\x12&.router_hosts.v1.DeleteSnapshotRequest\x1a'.router_hosts.v1.DeleteSnapshotResponse\x12O\n" +
	"\bLiveness\x12 .router_hosts.v1.LivenessRequest\x1a!.router_hosts.v1.LivenessResponse\x12R\n" +
	"\tReadiness\x12!.router_hosts.v1.ReadinessRequest\x1a\".router_hosts.v1.ReadinessResponse\x12I\n" +
	"\x06Health\x12\x1e.router_hosts.v1.HealthRequest\x1a\x1f.router_hosts.v1.HealthResponseBEZCgithub.com/fzymgc-house/router-hosts/api/v1/router_hosts/v1;hostsv1b\x06proto3"

var (
	file_router_hosts_v1_hosts_proto_rawDescOnce sync.Once
	file_router_hosts_v1_hosts_proto_rawDescData []byte
)

func file_router_hosts_v1_hosts_proto_rawDescGZIP() []byte {
	file_router_hosts_v1_hosts_proto_rawDescOnce.Do(func() {
		file_router_hosts_v1_hosts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_router_hosts_v1_hosts_proto_rawDesc), len(file_router_hosts_v1_hosts_proto_rawDesc)))
	})
	return file_router_hosts_v1_hosts_proto_rawDescData
}

var file_router_hosts_v1_hosts_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_router_hosts_v1_hosts_proto_goTypes = []any{
	(*HostEntry)(nil),                  // 0: router_hosts.v1.HostEntry
	(*AliasesUpdate)(nil),              // 1: router_hosts.v1.AliasesUpdate
	(*TagsUpdate)(nil),                 // 2: router_hosts.v1.TagsUpdate
	(*AddHostRequest)(nil),             // 3: router_hosts.v1.AddHostRequest
	(*AddHostResponse)(nil),            // 4: router_hosts.v1.AddHostResponse
	(*GetHostRequest)(nil),             // 5: router_hosts.v1.GetHostRequest
	(*GetHostResponse)(nil),            // 6: router_hosts.v1.GetHostResponse
	(*UpdateHostRequest)(nil),          // 7: router_hosts.v1.UpdateHostRequest
	(*UpdateHostResponse)(nil),         // 8: router_hosts.v1.UpdateHostResponse
	(*DeleteHostRequest)(nil),          // 9: router_hosts.v1.DeleteHostRequest
	(*DeleteHostResponse)(nil),         // 10: router_hosts.v1.DeleteHostResponse
	(*ListHostsRequest)(nil),           // 11: router_hosts.v1.ListHostsRequest
	(*ListHostsResponse)(nil),          // 12: router_hosts.v1.ListHostsResponse
	(*SearchHostsRequest)(nil),         // 13: router_hosts.v1.SearchHostsRequest
	(*SearchHostsResponse)(nil),        // 14: router_hosts.v1.SearchHostsResponse
	(*ImportHostsRequest)(nil),         // 15: router_hosts.v1.ImportHostsRequest
	(*ImportHostsResponse)(nil),        // 16: router_hosts.v1.ImportHostsResponse
	(*ExportHostsRequest)(nil),         // 17: router_hosts.v1.ExportHostsRequest
	(*ExportHostsResponse)(nil),        // 18: router_hosts.v1.ExportHostsResponse
	(*CreateSnapshotRequest)(nil),      // 19: router_hosts.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),     // 20: router_hosts.v1.CreateSnapshotResponse
	(*Snapshot)(nil),                   // 21: router_hosts.v1.Snapshot
	(*ListSnapshotsRequest)(nil),       // 22: router_hosts.v1.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),      // 23: router_hosts.v1.ListSnapshotsResponse
	(*RollbackToSnapshotRequest)(nil),  // 24: router_hosts.v1.RollbackToSnapshotRequest
	(*RollbackToSnapshotResponse)(nil), // 25: router_hosts.v1.RollbackToSnapshotResponse
	(*DeleteSnapshotRequest)(nil),      // 26: router_hosts.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),     // 27: router_hosts.v1.DeleteSnapshotResponse
	(*LivenessRequest)(nil),            // 28: router_hosts.v1.LivenessRequest
	(*LivenessResponse)(nil),           // 29: router_hosts.v1.LivenessResponse
	(*ReadinessRequest)(nil),           // 30: router_hosts.v1.ReadinessRequest
	(*ReadinessResponse)(nil),          // 31: router_hosts.v1.ReadinessResponse
	(*HealthRequest)(nil),              // 32: router_hosts.v1.HealthRequest
	(*HealthResponse)(nil),             // 33: router_hosts.v1.HealthResponse
	(*ServerInfo)(nil),                 // 34: router_hosts.v1.ServerInfo
	(*DatabaseHealth)(nil),             // 35: router_hosts.v1.DatabaseHealth
	(*AcmeHealth)(nil),                 // 36: router_hosts.v1.AcmeHealth
	(*HooksHealth)(nil),                // 37: router_hosts.v1.HooksHealth
	(*timestamppb.Timestamp)(nil),      // 38: google.protobuf.Timestamp
}
var file_router_hosts_v1_hosts_proto_depIdxs = []int32{
	38, // 0: router_hosts.v1.HostEntry.created_at:type_name -> google.protobuf.Timestamp
	38, // 1: router_hosts.v1.HostEntry.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: router_hosts.v1.AddHostResponse.entry:type_name -> router_hosts.v1.HostEntry
	0,  // 3: router_hosts.v1.GetHostResponse.entry:type_name -> router_hosts.v1.HostEntry
	1,  // 4: router_hosts.v1.UpdateHostRequest.aliases:type_name -> router_hosts.v1.AliasesUpdate
	2,  // 5: router_hosts.v1.UpdateHostRequest.tags:type_name -> router_hosts.v1.TagsUpdate
	0,  // 6: router_hosts.v1.UpdateHostResponse.entry:type_name -> router_hosts.v1.HostEntry
	0,  // 7: router_hosts.v1.ListHostsResponse.entry:type_name -> router_hosts.v1.HostEntry
	0,  // 8: router_hosts.v1.SearchHostsResponse.entry:type_name -> router_hosts.v1.HostEntry
	38, // 9: router_hosts.v1.Snapshot.created_at:type_name -> google.protobuf.Timestamp
	21, // 10: router_hosts.v1.ListSnapshotsResponse.snapshot:type_name -> router_hosts.v1.Snapshot
	34, // 11: router_hosts.v1.HealthResponse.server:type_name -> router_hosts.v1.ServerInfo
	35, // 12: router_hosts.v1.HealthResponse.database:type_name -> router_hosts.v1.DatabaseHealth
	36, // 13: router_hosts.v1.HealthResponse.acme:type_name -> router_hosts.v1.AcmeHealth
	37, // 14: router_hosts.v1.HealthResponse.hooks:type_name -> router_hosts.v1.HooksHealth
	3,  // 15: router_hosts.v1.HostsService.AddHost:input_type -> router_hosts.v1.AddHostRequest
	5,  // 16: router_hosts.v1.HostsService.GetHost:input_type -> router_hosts.v1.GetHostRequest
	7,  // 17: router_hosts.v1.HostsService.UpdateHost:input_type -> router_hosts.v1.UpdateHostRequest
	9,  // 18: router_hosts.v1.HostsService.DeleteHost:input_type -> router_hosts.v1.DeleteHostRequest
	11, // 19: router_hosts.v1.HostsService.ListHosts:input_type -> router_hosts.v1.ListHostsRequest
	13, // 20: router_hosts.v1.HostsService.SearchHosts:input_type -> router_hosts.v1.SearchHostsRequest
	15, // 21: router_hosts.v1.HostsService.ImportHosts:input_type -> router_hosts.v1.ImportHostsRequest
	17, // 22: router_hosts.v1.HostsService.ExportHosts:input_type -> router_hosts.v1.ExportHostsRequest
	19, // 23: router_hosts.v1.HostsService.CreateSnapshot:input_type -> router_hosts.v1.CreateSnapshotRequest
	22, // 24: router_hosts.v1.HostsService.ListSnapshots:input_type -> router_hosts.v1.ListSnapshotsRequest
	24, // 25: router_hosts.v1.HostsService.RollbackToSnapshot:input_type -> router_hosts.v1.RollbackToSnapshotRequest
	26, // 26: router_hosts.v1.HostsService.DeleteSnapshot:input_type -> router_hosts.v1.DeleteSnapshotRequest
	28, // 27: router_hosts.v1.HostsService.Liveness:input_type -> router_hosts.v1.LivenessRequest
	30, // 28: router_hosts.v1.HostsService.Readiness:input_type -> router_hosts.v1.ReadinessRequest
	32, // 29: router_hosts.v1.HostsService.Health:input_type -> router_hosts.v1.HealthRequest
	4,  // 30: router_hosts.v1.HostsService.AddHost:output_type -> router_hosts.v1.AddHostResponse
	6,  // 31: router_hosts.v1.HostsService.GetHost:output_type -> router_hosts.v1.GetHostResponse
	8,  // 32: router_hosts.v1.HostsService.UpdateHost:output_type -> router_hosts.v1.UpdateHostResponse
	10, // 33: router_hosts.v1.HostsService.DeleteHost:output_type -> router_hosts.v1.DeleteHostResponse
	12, // 34: router_hosts.v1.HostsService.ListHosts:output_type -> router_hosts.v1.ListHostsResponse
	14, // 35: router_hosts.v1.HostsService.SearchHosts:output_type -> router_hosts.v1.SearchHostsResponse
	16, // 36: router_hosts.v1.HostsService.ImportHosts:output_type -> router_hosts.v1.ImportHostsResponse
	18, // 37: router_hosts.v1.HostsService.ExportHosts:output_type -> router_hosts.v1.ExportHostsResponse
	20, // 38: router_hosts.v1.HostsService.CreateSnapshot:output_type -> router_hosts.v1.CreateSnapshotResponse
	23, // 39: router_hosts.v1.HostsService.ListSnapshots:output_type -> router_hosts.v1.ListSnapshotsResponse
	25, // 40: router_hosts.v1.HostsService.RollbackToSnapshot:output_type -> router_hosts.v1.RollbackToSnapshotResponse
	27, // 41: router_hosts.v1.HostsService.DeleteSnapshot:output_type -> router_hosts.v1.DeleteSnapshotResponse
	29, // 42: router_hosts.v1.HostsService.Liveness:output_type -> router_hosts.v1.LivenessResponse
	31, // 43: router_hosts.v1.HostsService.Readiness:output_type -> router_hosts.v1.ReadinessResponse
	33, // 44: router_hosts.v1.HostsService.Health:output_type -> router_hosts.v1.HealthResponse
	30, // [30:45] is the sub-list for method output_type
	15, // [15:30] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_router_hosts_v1_hosts_proto_init() }
func file_router_hosts_v1_hosts_proto_init() {
	if File_router_hosts_v1_hosts_proto != nil {
		return
	}
	file_router_hosts_v1_hosts_proto_msgTypes[0].OneofWrappers = []any{}
	file_router_hosts_v1_hosts_proto_msgTypes[3].OneofWrappers = []any{}
	file_router_hosts_v1_hosts_proto_msgTypes[7].OneofWrappers = []any{}
	file_router_hosts_v1_hosts_proto_msgTypes[11].OneofWrappers = []any{}
	file_router_hosts_v1_hosts_proto_msgTypes[15].OneofWrappers = []any{}
	file_router_hosts_v1_hosts_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_router_hosts_v1_hosts_proto_rawDesc), len(file_router_hosts_v1_hosts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_router_hosts_v1_hosts_proto_goTypes,
		DependencyIndexes: file_router_hosts_v1_hosts_proto_depIdxs,
		MessageInfos:      file_router_hosts_v1_hosts_proto_msgTypes,
	}.Build()
	File_router_hosts_v1_hosts_proto = out.File
	file_router_hosts_v1_hosts_proto_goTypes = nil
	file_router_hosts_v1_hosts_proto_depIdxs = nil
}
